import {
  ClientBusiness,
  ClientLead,
  ClientConversation,
  QualificationCriterion,
} from "@/types/leads";
import { DEFAULT_QUALIFICATION_CRITERIA } from "@/lib/leads/leads-config";

export const initialMockClients: ClientBusiness[] = [
  {
    id: "client_abc_school",
    businessName: "ABC International School",
    industry: "Education",
    location: "Srinagar, J&K",
    website: "https://abcschool.example.com",
    status: "Active",
    plan: "Growth OS + Admissions AI",
    mrr: 75000,
    assignedAgent: "Admissions Bot v2.4",
    activeChannels: ["Website Chat", "WhatsApp", "Instagram", "Email"],
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "client_alpine_hotel",
    businessName: "Alpine Grand Resort & Spa",
    industry: "Hospitality",
    location: "Gulmarg, Kashmir",
    website: "https://alpinegrand.example.com",
    status: "Active",
    plan: "Hospitality Direct Booking OS",
    mrr: 120000,
    assignedAgent: "Concierge Bot v3.1",
    activeChannels: ["Website Chat", "Instagram", "WhatsApp", "Facebook"],
    createdAt: "2026-01-15T10:30:00Z",
  },
  {
    id: "client_primecare_clinic",
    businessName: "PrimeCare Multi-Specialty Clinic",
    industry: "Healthcare",
    location: "South Extension, Delhi",
    website: "https://primecareclinic.example.com",
    status: "Active",
    plan: "Healthcare Triage & Intake OS",
    mrr: 95000,
    assignedAgent: "Patient Receptionist v2.2",
    activeChannels: ["WhatsApp", "Website Chat", "Phone"],
    createdAt: "2026-01-20T11:00:00Z",
  },
  {
    id: "client_veloce_interiors",
    businessName: "Veloce Luxury Interiors",
    industry: "Design & Real Estate",
    location: "Bandra West, Mumbai",
    website: "https://veloceinteriors.example.com",
    status: "Active",
    plan: "High-Ticket Lead OS",
    mrr: 110000,
    assignedAgent: "Consultation Scheduler v1.9",
    activeChannels: ["Instagram", "WhatsApp", "Website Chat"],
    createdAt: "2026-02-01T08:45:00Z",
  },
  {
    id: "client_apex_solar",
    businessName: "Apex Commercial Solar",
    industry: "CleanTech & Energy",
    location: "Whitefield, Bangalore",
    website: "https://apexsolar.example.com",
    status: "Onboarding",
    plan: "Commercial Acquisition OS",
    mrr: 65000,
    assignedAgent: "Solar Qualifier Bot v1.4",
    activeChannels: ["Website Chat", "Email", "Phone"],
    createdAt: "2026-02-14T14:20:00Z",
  },
];

function buildCriteria(overrides: Record<string, "Unknown" | "Yes" | "No" | "Not Applicable">): QualificationCriterion[] {
  return DEFAULT_QUALIFICATION_CRITERIA.map((c) => ({
    ...c,
    value: overrides[c.id] || "Unknown",
  }));
}

export const initialMockLeads: ClientLead[] = [
  {
    id: "lead_rahul_sharma",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    name: "Rahul Sharma",
    email: "rahul.sharma@familymail.example.com",
    phone: "+91 98765 43210",
    source: "Website",
    channel: "Website Chat",
    intent: "Admission",
    status: "QUALIFIED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 95,
    estimatedValue: 65000,
    tags: ["Grade 8", "CBSE", "Admissions 2026", "High Intent"],
    conversationId: "conv_rahul_abc",
    assignedTo: "Meera Sen (Admissions Head)",
    createdAt: "2026-03-28T10:14:00Z",
    updatedAt: "2026-03-29T11:30:00Z",
    lastActivityAt: "2 hours ago",
    nextFollowUpAt: "Tomorrow, 10:30 AM",
    notes: [
      {
        id: "note_1",
        author: "Meera Sen",
        content: "Father inquired for 8th grade. Confirmed family relocated to Srinagar. Scheduled campus tour for Friday.",
        createdAt: "2026-03-29T10:00:00Z",
      },
    ],
    activities: [
      {
        id: "act_1",
        title: "Campus Tour Scheduled",
        description: "Scheduled physical campus walk for Friday 11 AM with Principal.",
        type: "follow_up_scheduled",
        timestamp: "Yesterday, 3:30 PM",
        actor: "Team Member",
        channel: "Phone",
      },
      {
        id: "act_2",
        title: "Lead Qualified Automatically",
        description: "All 6 qualification criteria confirmed through website conversation.",
        type: "qualification_updated",
        timestamp: "Yesterday, 10:20 AM",
        actor: "AI Assistant",
        channel: "Website Chat",
      },
    ],
    aiSummary: "Parent seeking Grade 8 CBSE admission after relocation to Srinagar. Confirmed budget alignment and requested physical campus visit. (AI-generated summary — simulation)",
  },
  {
    id: "lead_sarah_johnson",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    name: "Sarah Johnson",
    email: "sarah.j@travelers.example.com",
    phone: "+1 (555) 728-1920",
    source: "Instagram",
    channel: "Instagram",
    intent: "Booking",
    status: "QUALIFIED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 92,
    estimatedValue: 48000,
    tags: ["Presidential Suite", "Anniversary", "Instagram Inbound", "Spa Package"],
    conversationId: "conv_sarah_alpine",
    assignedTo: "Bilal Wani (Front Desk Manager)",
    createdAt: "2026-03-29T08:30:00Z",
    updatedAt: "2026-03-29T09:15:00Z",
    lastActivityAt: "35 mins ago",
    nextFollowUpAt: "Today, 4:00 PM",
    notes: [
      {
        id: "note_2",
        author: "Bilal Wani",
        content: "Holding Suite 402 for upcoming weekend. Waiting for final guest ID upload.",
        createdAt: "2026-03-29T09:10:00Z",
      },
    ],
    activities: [
      {
        id: "act_3",
        title: "Reservation Link Sent",
        description: "AI Concierge delivered instant WhatsApp reservation checkout link.",
        type: "ai_response",
        timestamp: "Today, 9:00 AM",
        actor: "AI Assistant",
        channel: "Instagram",
      },
    ],
    aiSummary: "Couple visiting Gulmarg for 3-night anniversary stay. Interested in Presidential Suite with spa inclusions. Pre-held suite on calendar. (AI-generated summary — simulation)",
  },
  {
    id: "lead_michael_brown",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    name: "Michael Brown",
    email: "m.brown@corphealth.example.com",
    phone: "+91 98112 34567",
    source: "WhatsApp",
    channel: "WhatsApp",
    intent: "Appointment",
    status: "NEW",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Unknown",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 72,
    estimatedValue: 12500,
    tags: ["Executive Health", "Full Checkup", "WhatsApp Inbound"],
    conversationId: "conv_michael_primecare",
    assignedTo: "Dr. Ananya Verma",
    createdAt: "2026-03-29T11:00:00Z",
    updatedAt: "2026-03-29T11:20:00Z",
    lastActivityAt: "10 mins ago",
    notes: [],
    activities: [
      {
        id: "act_4",
        title: "Inbound WhatsApp Inquired",
        description: "Customer asked for annual executive health package pricing.",
        type: "message_received",
        timestamp: "10 mins ago",
        actor: "Visitor",
        channel: "WhatsApp",
      },
    ],
    aiSummary: "Inquiring about executive health checkup packages for self and spouse. Seeking appointment slot for upcoming Tuesday. (AI-generated summary — simulation)",
  },
  {
    id: "lead_emma_davis",
    clientId: "client_veloce_interiors",
    clientName: "Veloce Luxury Interiors",
    name: "Emma Davis",
    email: "emma.davis@designlovers.example.com",
    phone: "+91 99201 88412",
    source: "Facebook",
    channel: "Facebook",
    intent: "Service Inquiry",
    status: "FOLLOW_UP",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Unknown",
      decision_maker: "Unknown",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 65,
    estimatedValue: 350000,
    tags: ["4BHK Remodel", "Bandra", "High Value", "Interior"],
    conversationId: "conv_emma_veloce",
    assignedTo: "Elena Rostova (Lead Designer)",
    createdAt: "2026-03-27T14:00:00Z",
    updatedAt: "2026-03-28T16:20:00Z",
    lastActivityAt: "1 day ago",
    nextFollowUpAt: "Tomorrow, 2:00 PM",
    notes: [],
    activities: [
      {
        id: "act_5",
        title: "Portfolio Brochure Shared",
        description: "Delivered 2026 Coastal Luxury lookbook over Messenger.",
        type: "ai_response",
        timestamp: "Yesterday",
        actor: "AI Assistant",
        channel: "Facebook",
      },
    ],
    aiSummary: "Homeowner remodeling a 4BHK apartment in Bandra. Estimated budget ₹30–40 Lakhs. Follow-up scheduled to confirm on-site consultation. (AI-generated summary — simulation)",
  },
  {
    id: "lead_vikram_patel",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    name: "Vikram Patel",
    email: "vikram.p@patelholdings.example.com",
    phone: "+91 97654 32109",
    source: "Website",
    channel: "Website Chat",
    intent: "Admission",
    status: "QUALIFYING",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Unknown",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 68,
    estimatedValue: 85000,
    tags: ["Grade 11", "Science Stream", "Hostel Required"],
    conversationId: "conv_vikram_abc",
    assignedTo: "Meera Sen",
    createdAt: "2026-03-29T07:15:00Z",
    updatedAt: "2026-03-29T08:00:00Z",
    lastActivityAt: "3 hours ago",
    notes: [],
    activities: [],
    aiSummary: "Prospective student parent asking about Grade 11 Science curriculum (PCM + Computer Science) and residential boarding facilities. (AI-generated summary — simulation)",
  },
  {
    id: "lead_ananya_desai",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    name: "Ananya Desai",
    email: "ananya.desai@corporatewellness.example.com",
    phone: "+91 98200 11223",
    source: "Instagram",
    channel: "Instagram",
    intent: "Booking",
    status: "HUMAN_HANDOFF",
    qualificationStatus: "NEEDS_HUMAN_REVIEW",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "No",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 74,
    estimatedValue: 180000,
    tags: ["Corporate Retreat", "15 Rooms", "Human Handoff", "High Value"],
    conversationId: "conv_ananya_alpine",
    assignedTo: "Bilal Wani",
    createdAt: "2026-03-28T18:30:00Z",
    updatedAt: "2026-03-29T06:45:00Z",
    lastActivityAt: "4 hours ago",
    nextFollowUpAt: "Today, 1:30 PM",
    notes: [
      {
        id: "note_3",
        author: "Bilal Wani",
        content: "Corporate offsite booking requiring custom food & beverage quote and conference room setup.",
        createdAt: "2026-03-29T07:00:00Z",
      },
    ],
    activities: [
      {
        id: "act_6",
        title: "Escalated to Human Sales Team",
        description: "Group booking exceeds standard automated booking limits (>10 rooms).",
        type: "human_handoff",
        timestamp: "Today, 6:45 AM",
        actor: "AI Assistant",
        channel: "Instagram",
      },
    ],
    aiSummary: "Inquiry for 15 Deluxe Rooms for corporate leadership retreat in April. Escalated for customized group rates and banquet arrangements. (AI-generated summary — simulation)",
  },
  {
    id: "lead_rajesh_gupta",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    name: "Rajesh Gupta",
    email: "rajesh.gupta@delhiops.example.com",
    phone: "+91 99110 55443",
    source: "WhatsApp",
    channel: "WhatsApp",
    intent: "Appointment",
    status: "CONVERTED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 100,
    estimatedValue: 15000,
    tags: ["Cardiology", "Confirmed Appointment", "Converted"],
    conversationId: "conv_rajesh_primecare",
    assignedTo: "Dr. Ananya Verma",
    createdAt: "2026-03-26T09:00:00Z",
    updatedAt: "2026-03-27T10:00:00Z",
    lastActivityAt: "2 days ago",
    notes: [],
    activities: [
      {
        id: "act_7",
        title: "Appointment Confirmed",
        description: "Confirmed slot for Dr. Verma OPD on Thursday 4:30 PM. Token #14.",
        type: "status_changed",
        timestamp: "2 days ago",
        actor: "Team Member",
        channel: "WhatsApp",
      },
    ],
    aiSummary: "Cardiology consultation appointment booked and confirmed via WhatsApp bot. Payment advance confirmed. (AI-generated summary — simulation)",
  },
  {
    id: "lead_david_miller",
    clientId: "client_apex_solar",
    clientName: "Apex Commercial Solar",
    name: "David Miller",
    email: "david@millermfg.example.com",
    phone: "+91 88800 99881",
    source: "Website",
    channel: "Website Chat",
    intent: "Service Inquiry",
    status: "QUALIFIED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 90,
    estimatedValue: 550000,
    tags: ["100kW Rooftop", "Manufacturing Plant", "CleanTech"],
    conversationId: "conv_david_apex",
    assignedTo: "Sunil Rao (Solar Engineer)",
    createdAt: "2026-03-27T11:20:00Z",
    updatedAt: "2026-03-28T09:30:00Z",
    lastActivityAt: "1 day ago",
    notes: [],
    activities: [],
    aiSummary: "Manufacturing plant owner seeking 100kW commercial rooftop solar setup in Peenya Industrial Area. Monthly electricity bill ₹1.8 Lakhs. (AI-generated summary — simulation)",
  },
  {
    id: "lead_ayaan_khan",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    name: "Ayaan Khan",
    email: "ayaan@example.com",
    phone: "+91 98765 43210",
    source: "Instagram",
    channel: "WhatsApp",
    intent: "Booking",
    status: "QUALIFIED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 94,
    estimatedValue: 75000,
    tags: ["Cross-Channel Unified", "Presidential Suite", "VIP Guest", "Instagram + WA"],
    conversationId: "conv_ayaan_wa",
    assignedTo: "Bilal Wani",
    createdAt: "2026-03-27T11:00:00Z",
    updatedAt: "2026-03-29T10:15:00Z",
    lastActivityAt: "15 mins ago",
    nextFollowUpAt: "Tomorrow, 11:00 AM",
    notes: [
      {
        id: "note_ayaan_1",
        author: "Bilal Wani",
        content: "Customer first reached out via Instagram DM inquiring about weekend rates. Followed up on WhatsApp with phone number verification. Presidential Suite reserved pending deposit.",
        createdAt: "2026-03-29T10:20:00Z",
      },
    ],
    activities: [
      {
        id: "act_ay_1",
        title: "Channel Switched to WhatsApp",
        description: "Customer transitioned from Instagram (@ayaan_demo) to WhatsApp (+91 98765 43210). Identity automatically linked.",
        type: "message_received",
        timestamp: "Today, 10:15 AM",
        actor: "Visitor",
        channel: "WhatsApp",
      },
      {
        id: "act_ay_2",
        title: "Initial Instagram DM",
        description: "Inquired about Presidential Suite pricing for weekend getaway.",
        type: "message_received",
        timestamp: "2 days ago",
        actor: "Visitor",
        channel: "Instagram",
      },
    ],
    aiSummary: "Cross-channel unified VIP customer. Reached out initially via Instagram DM (@ayaan_demo) and subsequently on WhatsApp (+91 98765 43210). Booking confirmed for Presidential Suite. (AI-generated summary — simulation)",
  },
  {
    id: "lead_dr_sana_mir",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    name: "Dr. Sana Mir",
    email: "sana.mir@healthkashmir.org",
    phone: "+91 94190 88771",
    source: "Email",
    channel: "Email",
    intent: "Admission",
    status: "NEW",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Unknown",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 62,
    estimatedValue: 65000,
    tags: ["Grade 5", "Email Inquiry", "Transport Query"],
    conversationId: "conv_email_inquiry_abc",
    assignedTo: "Meera Sen",
    createdAt: "2026-03-29T08:00:00Z",
    updatedAt: "2026-03-29T08:00:00Z",
    lastActivityAt: "4 hours ago",
    notes: [],
    activities: [],
    aiSummary: "Physician inquiring via formal email relay regarding Grade 5 admission and school bus route availability from Nishat. (AI-generated summary — simulation)",
  },
  {
    id: "lead_karan_mehra",
    clientId: "client_veloce_interiors",
    clientName: "Veloce Luxury Interiors",
    name: "Karan Mehra",
    email: "karan.m@mumbaibiz.example.com",
    phone: "+91 98200 44332",
    source: "WhatsApp",
    channel: "WhatsApp",
    intent: "Service Inquiry",
    status: "QUALIFYING",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Unknown",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 78,
    estimatedValue: 280000,
    tags: ["Penthouse", "Worli", "WhatsApp Inbound"],
    conversationId: "conv_karan_wa",
    assignedTo: "Elena Rostova",
    createdAt: "2026-03-28T15:00:00Z",
    updatedAt: "2026-03-29T09:30:00Z",
    lastActivityAt: "3 hours ago",
    notes: [],
    activities: [],
    aiSummary: "Penthouse owner in Worli seeking modern Italian luxury interior makeover. Discussed preliminary budget bracket of ₹25-30 Lakhs. (AI-generated summary — simulation)",
  },
  {
    id: "lead_priya_sharma",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    name: "Priya Sharma",
    email: "priya.s@travelworld.example.com",
    phone: "+91 98110 99887",
    source: "Instagram",
    channel: "Instagram",
    intent: "Booking",
    status: "FOLLOW_UP",
    qualificationStatus: "IN_PROGRESS",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Unknown",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 70,
    estimatedValue: 42000,
    tags: ["Honeymoon", "Instagram Story Reply", "Follow-Up"],
    conversationId: "conv_priya_ig",
    assignedTo: "Bilal Wani",
    createdAt: "2026-03-28T16:00:00Z",
    updatedAt: "2026-03-29T10:00:00Z",
    lastActivityAt: "2 hours ago",
    nextFollowUpAt: "Today, 5:00 PM",
    notes: [],
    activities: [],
    aiSummary: "Responded to Instagram story showcasing mountain view jacuzzi cottage. Requested honeymoon bundle package details. (AI-generated summary — simulation)",
  },
  {
    id: "lead_tarun_verma",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    name: "Tarun Verma",
    email: "tarun.verma@techsolutions.example.com",
    phone: "+91 99887 66554",
    source: "Website",
    channel: "Website Chat",
    intent: "Appointment",
    status: "CONVERTED",
    qualificationStatus: "QUALIFIED",
    qualificationCriteria: buildCriteria({
      need_identified: "Yes",
      budget_discussed: "Yes",
      timeline_known: "Yes",
      decision_maker: "Yes",
      service_fit: "Yes",
      contact_available: "Yes",
    }),
    score: 100,
    estimatedValue: 18500,
    tags: ["Orthopedic", "Website Chat", "Confirmed"],
    conversationId: "conv_tarun_web",
    assignedTo: "Dr. Ananya Verma",
    createdAt: "2026-03-26T14:00:00Z",
    updatedAt: "2026-03-27T11:00:00Z",
    lastActivityAt: "2 days ago",
    notes: [],
    activities: [],
    aiSummary: "Patient booked knee consultation and diagnostic X-Ray package via web chat widget. Appointment confirmed for Saturday 11 AM. (AI-generated summary — simulation)",
  },
];

export const initialMockConversations: ClientConversation[] = [
  {
    id: "conv_rahul_abc",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    leadId: "lead_rahul_sharma",
    leadName: "Rahul Sharma",
    leadContact: "+91 98765 43210",
    channel: "Website Chat",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_r1",
        conversationId: "conv_rahul_abc",
        sender: "lead",
        content: "Hello, I am looking for admission details for Grade 8 for the upcoming academic session.",
        timestamp: "10:14 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_r2",
        conversationId: "conv_rahul_abc",
        sender: "ai",
        content: "Welcome to ABC International School! Admissions for Grade 8 CBSE are currently open. We offer advanced STEM labs, sports coaching, and language clubs. Would you like to know about the admission procedure and fee structure?",
        timestamp: "10:14 AM",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_r3",
        conversationId: "conv_rahul_abc",
        sender: "lead",
        content: "Yes please, what is the annual fee and how can we book a campus tour? My name is Rahul Sharma and my number is +91 98765 43210.",
        timestamp: "10:16 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_r4",
        conversationId: "conv_rahul_abc",
        sender: "ai",
        content: "Thank you Mr. Sharma! The annual fee for Grade 8 is approximately ₹65,000 per term. I have recorded your details and registered a priority admission inquiry. Our admissions head, Mrs. Meera Sen, has scheduled a campus tour slot for this Friday at 11:00 AM. Would that time work for your family?",
        timestamp: "10:17 AM",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_r5",
        conversationId: "conv_rahul_abc",
        sender: "lead",
        content: "Friday at 11:00 AM works perfectly. See you then!",
        timestamp: "10:18 AM",
        aiGenerated: false,
        messageType: "text",
      },
    ],
    intent: "Admission",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    extractedInfo: {
      name: "Rahul Sharma",
      phone: "+91 98765 43210",
      intent: "Admission",
      requestedService: "Grade 8 CBSE Admission & Campus Tour",
      preferredDate: "Friday at 11:00 AM",
      reviewStatus: "accepted",
      confidence: "High",
    },
    suggestedNextAction: "Prepare campus tour badge and student prospectus packet.",
    assignedTo: "Meera Sen",
    startedAt: "2026-03-29T10:14:00Z",
    updatedAt: "2026-03-29T10:18:00Z",
    lastMessageSnippet: "Friday at 11:00 AM works perfectly. See you then!",
    lastMessageAt: "2 hours ago",
    unreadCount: 0,
  },
  {
    id: "conv_sarah_alpine",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    leadId: "lead_sarah_johnson",
    leadName: "Sarah Johnson",
    leadContact: "+1 (555) 728-1920",
    channel: "Instagram",
    channelHandle: "@sarahj_travels",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_s1",
        conversationId: "conv_sarah_alpine",
        sender: "lead",
        content: "Hi there! I saw your post on the Presidential Suite. Do you have availability for this upcoming weekend?",
        timestamp: "8:30 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_s2",
        conversationId: "conv_sarah_alpine",
        sender: "ai",
        content: "Hello Sarah! Yes, the Presidential Suite is available for 2 nights this weekend. It includes panoramic Himalayan views, private heated jacuzzi, and complimentary champagne breakfast. Would you like to check our special Anniversary Package?",
        timestamp: "8:30 AM",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_s3",
        conversationId: "conv_sarah_alpine",
        sender: "lead",
        content: "Yes! What are the rates with the spa package included?",
        timestamp: "8:32 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_s4",
        conversationId: "conv_sarah_alpine",
        sender: "ai",
        content: "The package is ₹24,000/night all-inclusive. I have placed a complimentary 2-hour hold on Suite 402 for you. May I share the instant WhatsApp reservation link with your phone number +1 (555) 728-1920?",
        timestamp: "8:33 AM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Booking",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    extractedInfo: {
      name: "Sarah Johnson",
      phone: "+1 (555) 728-1920",
      intent: "Booking",
      requestedService: "Presidential Suite with Spa",
      preferredDate: "this weekend",
      reviewStatus: "accepted",
      confidence: "High",
    },
    suggestedNextAction: "Check WhatsApp checkout link status and confirm arrival time.",
    assignedTo: "Bilal Wani",
    startedAt: "2026-03-29T08:30:00Z",
    updatedAt: "2026-03-29T08:33:00Z",
    lastMessageSnippet: "May I share the instant WhatsApp reservation link...",
    lastMessageAt: "35 mins ago",
    unreadCount: 1,
  },
  {
    id: "conv_michael_primecare",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    leadId: "lead_michael_brown",
    leadName: "Michael Brown",
    leadContact: "+91 98112 34567",
    channel: "WhatsApp",
    channelHandle: "+91 98112 34567",
    status: "Needs Attention",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_m1",
        conversationId: "conv_michael_primecare",
        sender: "lead",
        content: "Hi PrimeCare, can you tell me more about your executive full body health checkup package?",
        timestamp: "11:00 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_m2",
        conversationId: "conv_michael_primecare",
        sender: "ai",
        content: "Hello! Our Comprehensive Executive Screening covers 68 parameters including cardiac lipid panel, liver/kidney profiles, ultrasound, ECG, and 1-on-1 consultation with senior physician Dr. Ananya Verma. Digital reports are ready in 6 hours.",
        timestamp: "11:00 AM",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_m3",
        conversationId: "conv_michael_primecare",
        sender: "lead",
        content: "My name is Michael Brown. Do you have morning slots available on Tuesday around 9 AM?",
        timestamp: "11:15 AM",
        aiGenerated: false,
        messageType: "text",
      },
    ],
    intent: "Appointment",
    sentiment: "neutral",
    qualificationStatus: "IN_PROGRESS",
    extractedInfo: {
      name: "Michael Brown",
      phone: "+91 98112 34567",
      intent: "Appointment",
      requestedService: "Executive Health Checkup",
      preferredDate: "Tuesday around 9 AM",
      reviewStatus: "pending",
      confidence: "High",
    },
    suggestedNextAction: "Confirm 9 AM Tuesday fasting slot with laboratory.",
    assignedTo: "Dr. Ananya Verma",
    startedAt: "2026-03-29T11:00:00Z",
    updatedAt: "2026-03-29T11:15:00Z",
    lastMessageSnippet: "My name is Michael Brown. Do you have morning slots available...",
    lastMessageAt: "10 mins ago",
    unreadCount: 1,
  },
  {
    id: "conv_ananya_alpine",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    leadId: "lead_ananya_desai",
    leadName: "Ananya Desai",
    leadContact: "+91 98200 11223",
    channel: "Instagram",
    channelHandle: "@ananya_desai",
    status: "Human Active",
    aiMode: "human_takeover",
    autoCaptureEnabled: false,
    handoff: {
      requestedAt: "2026-03-29T06:45:00Z",
      reason: "Visitor requested human specialist for 15-room bulk booking.",
      status: "accepted",
    },
    messages: [
      {
        id: "m_a1",
        conversationId: "conv_ananya_alpine",
        sender: "lead",
        content: "Hi, I need to book 15 rooms for an executive leadership retreat for 3 nights in April. Can I speak to a human manager for corporate pricing?",
        timestamp: "6:44 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_a2",
        conversationId: "conv_ananya_alpine",
        sender: "ai",
        content: "I'd be glad to connect you! I am notifying our General Manager, Mr. Bilal Wani, to handle your group retreat personally.",
        timestamp: "6:45 AM",
        aiGenerated: true,
        messageType: "handoff",
      },
      {
        id: "m_a3",
        conversationId: "conv_ananya_alpine",
        sender: "human",
        content: "Hello Ananya, this is Bilal Wani, GM at Alpine Grand. I would be happy to put together a private group proposal with banquet hall access. What dates in April are you targeting?",
        timestamp: "6:50 AM",
        aiGenerated: false,
        messageType: "text",
      },
    ],
    intent: "Booking",
    sentiment: "positive",
    qualificationStatus: "NEEDS_HUMAN_REVIEW",
    extractedInfo: {
      name: "Ananya Desai",
      phone: "+91 98200 11223",
      intent: "Booking",
      requestedService: "15-Room Corporate Retreat",
      preferredDate: "in April",
      reviewStatus: "accepted",
      confidence: "High",
    },
    suggestedNextAction: "Send custom PDF corporate rate sheet and conference menu.",
    assignedTo: "Bilal Wani",
    startedAt: "2026-03-29T06:44:00Z",
    updatedAt: "2026-03-29T06:50:00Z",
    lastMessageSnippet: "Hello Ananya, this is Bilal Wani, GM at Alpine Grand...",
    lastMessageAt: "4 hours ago",
    unreadCount: 0,
  },
  {
    id: "conv_in_flight_visitor",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    leadName: "Anonymous Visitor",
    channel: "Website Chat",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_v1",
        conversationId: "conv_in_flight_visitor",
        sender: "lead",
        content: "Where is the school located and what are your visiting hours?",
        timestamp: "12:05 PM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_v2",
        conversationId: "conv_in_flight_visitor",
        sender: "ai",
        content: "We are located at Boulevard Road, Srinagar (near Dal Lake). Our campus reception is open Monday through Saturday from 9:00 AM to 4:00 PM for parent visits. Would you like to schedule an appointment?",
        timestamp: "12:05 PM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Information Request",
    sentiment: "neutral",
    qualificationStatus: "NOT_STARTED",
    suggestedNextAction: "Wait for visitor response or prompt for student grade inquiry.",
    assignedTo: "Admissions Bot v2.4",
    startedAt: "2026-03-29T12:05:00Z",
    updatedAt: "2026-03-29T12:05:00Z",
    lastMessageSnippet: "We are located at Boulevard Road, Srinagar...",
    lastMessageAt: "Just now",
    unreadCount: 0,
  },
  {
    id: "conv_ayaan_wa",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    leadId: "lead_ayaan_khan",
    leadName: "Ayaan Khan",
    leadContact: "+91 98765 43210",
    channel: "WhatsApp",
    channelHandle: "+91 98765 43210",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_ay_w1",
        conversationId: "conv_ayaan_wa",
        sender: "lead",
        content: "Hi Bilal, I spoke to you on Instagram earlier (@ayaan_demo). I want to confirm the presidential suite booking for this weekend.",
        timestamp: "10:15 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_ay_w2",
        conversationId: "conv_ayaan_wa",
        sender: "ai",
        content: "Hello Ayaan! Welcome back. We have your inquiry from Instagram linked to your profile. The Presidential Suite is reserved for this Friday–Sunday with complimentary airport pickup and private spa access. Shall I generate the reservation voucher link?",
        timestamp: "10:16 AM",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_ay_w3",
        conversationId: "conv_ayaan_wa",
        sender: "lead",
        content: "Yes please, send the payment link and details for 2 guests.",
        timestamp: "10:18 AM",
        aiGenerated: false,
        messageType: "text",
      },
    ],
    intent: "Booking",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    extractedInfo: {
      name: "Ayaan Khan",
      phone: "+91 98765 43210",
      email: "ayaan@example.com",
      requestedService: "Presidential Suite Weekend",
      preferredDate: "This Friday–Sunday",
      reviewStatus: "accepted",
      confidence: "High",
    },
    suggestedNextAction: "Send WhatsApp secure payment voucher link.",
    assignedTo: "Bilal Wani",
    startedAt: "2026-03-29T10:15:00Z",
    updatedAt: "2026-03-29T10:18:00Z",
    lastMessageSnippet: "Yes please, send the payment link and details for 2 guests.",
    lastMessageAt: "15 mins ago",
    unreadCount: 1,
  },
  {
    id: "conv_ayaan_ig",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    leadId: "lead_ayaan_khan",
    leadName: "Ayaan Khan",
    leadContact: "@ayaan_demo",
    channel: "Instagram",
    channelHandle: "@ayaan_demo",
    status: "Closed",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_ay_i1",
        conversationId: "conv_ayaan_ig",
        sender: "lead",
        content: "Hi, what are your presidential suite prices for this month?",
        timestamp: "2 days ago",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_ay_i2",
        conversationId: "conv_ayaan_ig",
        sender: "ai",
        content: "Hello @ayaan_demo! Our Presidential Suite is ₹38,000/night + taxes including breakfast buffet, valley view balcony, and private sauna. Would you like to check dates for this weekend?",
        timestamp: "2 days ago",
        aiGenerated: true,
        messageType: "text",
      },
      {
        id: "m_ay_i3",
        conversationId: "conv_ayaan_ig",
        sender: "lead",
        content: "Sounds great, can I ping you on WhatsApp to share ID and finalize?",
        timestamp: "2 days ago",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_ay_i4",
        conversationId: "conv_ayaan_ig",
        sender: "ai",
        content: "Certainly! You can WhatsApp our concierge desk directly at +91 94191 55667.",
        timestamp: "2 days ago",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Pricing Inquiry",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    suggestedNextAction: "Transitioned to WhatsApp for booking closure.",
    assignedTo: "Bilal Wani",
    startedAt: "2026-03-27T11:00:00Z",
    updatedAt: "2026-03-27T11:45:00Z",
    lastMessageSnippet: "Certainly! You can WhatsApp our concierge desk directly...",
    lastMessageAt: "2 days ago",
    unreadCount: 0,
  },
  {
    id: "conv_email_inquiry_abc",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    leadId: "lead_dr_sana_mir",
    leadName: "Dr. Sana Mir",
    leadContact: "sana.mir@healthkashmir.org",
    channel: "Email",
    channelHandle: "sana.mir@healthkashmir.org",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_em_1",
        conversationId: "conv_email_inquiry_abc",
        sender: "lead",
        content: "Subject: Admission query for Grade 5 & Transportation routes\n\nDear Admissions Office,\n\nI am writing to inquire regarding admission availability for my daughter in Grade 5 for the coming term. Also, do you operate school bus pick-up routes covering Nishat / Foreshore Road area?\n\nSincerely,\nDr. Sana Mir\nPh: +91 94190 88771",
        timestamp: "08:00 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_em_2",
        conversationId: "conv_email_inquiry_abc",
        sender: "ai",
        content: "Dear Dr. Sana Mir,\n\nThank you for reaching out to ABC International School. Yes, Grade 5 seats are available. Our Route 4 bus connects Foreshore Road and Nishat directly to campus with GPS-tracked student transit. We have sent the admission prospectus to your email.",
        timestamp: "08:02 AM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Admission",
    sentiment: "neutral",
    qualificationStatus: "IN_PROGRESS",
    extractedInfo: {
      name: "Dr. Sana Mir",
      email: "sana.mir@healthkashmir.org",
      phone: "+91 94190 88771",
      requestedService: "Grade 5 Admission + Route 4 Transport",
      reviewStatus: "accepted",
      confidence: "High",
    },
    suggestedNextAction: "Review transport seating availability and follow up with registration form.",
    assignedTo: "Meera Sen",
    startedAt: "2026-03-29T08:00:00Z",
    updatedAt: "2026-03-29T08:02:00Z",
    lastMessageSnippet: "Dear Dr. Sana Mir, Thank you for reaching out to ABC...",
    lastMessageAt: "4 hours ago",
    unreadCount: 0,
  },
  {
    id: "conv_karan_wa",
    clientId: "client_veloce_interiors",
    clientName: "Veloce Luxury Interiors",
    leadId: "lead_karan_mehra",
    leadName: "Karan Mehra",
    leadContact: "+91 98200 44332",
    channel: "WhatsApp",
    channelHandle: "+91 98200 44332",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_kw_1",
        conversationId: "conv_karan_wa",
        sender: "lead",
        content: "Hi Veloce team, got your reference from an architectural feature. I have a 3,200 sq.ft penthouse in Worli ready for full interior design.",
        timestamp: "09:30 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_kw_2",
        conversationId: "conv_karan_wa",
        sender: "ai",
        content: "Hello Karan! Congratulations on your Worli penthouse. Our lead designer Elena Rostova specializes in modern Italian minimalism and coastal luxury. Would you like to review our South Mumbai portfolio and schedule a preliminary consultation?",
        timestamp: "09:31 AM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Service Inquiry",
    sentiment: "positive",
    qualificationStatus: "IN_PROGRESS",
    suggestedNextAction: "Schedule architectural consultation with Elena Rostova.",
    assignedTo: "Elena Rostova",
    startedAt: "2026-03-29T09:30:00Z",
    updatedAt: "2026-03-29T09:31:00Z",
    lastMessageSnippet: "Hello Karan! Congratulations on your Worli penthouse...",
    lastMessageAt: "3 hours ago",
    unreadCount: 0,
  },
  {
    id: "conv_priya_ig",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    leadId: "lead_priya_sharma",
    leadName: "Priya Sharma",
    leadContact: "@priya.s_travels",
    channel: "Instagram",
    channelHandle: "@priya.s_travels",
    status: "Active",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_pi_1",
        conversationId: "conv_priya_ig",
        sender: "lead",
        content: "Loved your story featuring the jacuzzi chalet! How much is the 3-night honeymoon package?",
        timestamp: "10:00 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_pi_2",
        conversationId: "conv_priya_ig",
        sender: "ai",
        content: "Hi Priya! Our 3-night Honeymoon Serenity package is ₹42,000 including candle-lit dinner, jacuzzi chalet stay, and private cable car passes. Which month are you planning for?",
        timestamp: "10:01 AM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Booking",
    sentiment: "positive",
    qualificationStatus: "IN_PROGRESS",
    suggestedNextAction: "Follow up with honeymoon brochure and custom travel dates.",
    assignedTo: "Bilal Wani",
    startedAt: "2026-03-29T10:00:00Z",
    updatedAt: "2026-03-29T10:01:00Z",
    lastMessageSnippet: "Hi Priya! Our 3-night Honeymoon Serenity package...",
    lastMessageAt: "2 hours ago",
    unreadCount: 1,
  },
  {
    id: "conv_tarun_web",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    leadId: "lead_tarun_verma",
    leadName: "Tarun Verma",
    leadContact: "+91 99887 66554",
    channel: "Website Chat",
    channelHandle: "Website Visitor #4401",
    status: "Closed",
    aiMode: "autonomous",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_tw_1",
        conversationId: "conv_tarun_web",
        sender: "lead",
        content: "Need to book knee doctor consultation for Saturday morning.",
        timestamp: "11:00 AM",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_tw_2",
        conversationId: "conv_tarun_web",
        sender: "ai",
        content: "Certainly Tarun! We have Dr. Verma (Senior Orthopedic Surgeon) available Saturday at 11:30 AM. Booking confirmed with Token #08.",
        timestamp: "11:02 AM",
        aiGenerated: true,
        messageType: "text",
      },
    ],
    intent: "Appointment",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    suggestedNextAction: "Appointment confirmed. Patient attended.",
    assignedTo: "Dr. Ananya Verma",
    startedAt: "2026-03-27T11:00:00Z",
    updatedAt: "2026-03-27T11:02:00Z",
    lastMessageSnippet: "Certainly Tarun! We have Dr. Verma available Saturday...",
    lastMessageAt: "2 days ago",
    unreadCount: 0,
  },
  {
    id: "conv_david_apex",
    clientId: "client_apex_solar",
    clientName: "Apex Commercial Solar",
    leadId: "lead_david_miller",
    leadName: "David Miller",
    leadContact: "+91 88800 99881",
    channel: "Website Chat",
    channelHandle: "Website Visitor #892",
    status: "Active",
    aiMode: "human_takeover",
    autoCaptureEnabled: true,
    messages: [
      {
        id: "m_da_1",
        conversationId: "conv_david_apex",
        sender: "lead",
        content: "We have an industrial manufacturing facility in Peenya. Current power bill is ~1.8L/mo. Looking for a 100kW rooftop solar feasibility study.",
        timestamp: "Yesterday",
        aiGenerated: false,
        messageType: "text",
      },
      {
        id: "m_da_2",
        conversationId: "conv_david_apex",
        sender: "ai",
        content: "Hello David! A 100kW system typically cuts manufacturing power costs by 65–75% with a payback period under 3.5 years. Escalating your facility details to our senior solar engineer Sunil Rao.",
        timestamp: "Yesterday",
        aiGenerated: true,
        messageType: "handoff",
      },
    ],
    intent: "Service Inquiry",
    sentiment: "positive",
    qualificationStatus: "QUALIFIED",
    suggestedNextAction: "Sunil Rao conducting site feasibility study.",
    assignedTo: "Sunil Rao",
    startedAt: "2026-03-28T09:20:00Z",
    updatedAt: "2026-03-28T09:30:00Z",
    lastMessageSnippet: "Hello David! A 100kW system typically cuts...",
    lastMessageAt: "1 day ago",
    unreadCount: 0,
  },
];
