import { Conversation } from "@/types";

export const mockRecentConversations: Conversation[] = [
  {
    id: "conv_sarah",
    contactName: "Sarah Johnson",
    contactRole: "Guest / Prospective Customer",
    companyName: "Alpine Grand Hotel (Client System)",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    channel: "Instagram",
    channelHandle: "@sarahj_travels",
    unreadCount: 1,
    lastMessageSnippet: "Do you have availability this weekend?",
    lastMessageAt: "4 mins ago",
    status: "Qualified",
    aiIntent: "high_intent",
    aiHandled: true,
    messages: [
      {
        id: "m_s1",
        sender: "lead",
        content: "Hi there! I saw your post about the Presidential Suite. Do you have availability this weekend?",
        timestamp: "10:14 AM",
        sentiment: "positive",
      },
      {
        id: "m_s2",
        sender: "ai_agent",
        content: "Hello Sarah! Yes, we have the Presidential Suite and Mountain View Deluxe available this weekend. For how many guests will you be booking?",
        timestamp: "10:14 AM",
        isAiGenerated: true,
      },
      {
        id: "m_s3",
        sender: "lead",
        content: "Just two of us for an anniversary getaway. Can we get the package with spa access included?",
        timestamp: "10:16 AM",
        sentiment: "positive",
      },
      {
        id: "m_s4",
        sender: "ai_agent",
        content: "Absolutely! The Anniversary Package includes complimentary spa access and sunset champagne. I have pre-held the suite for you. Would you like me to send the instant reservation link?",
        timestamp: "10:17 AM",
        isAiGenerated: true,
      },
      {
        id: "m_s5",
        sender: "lead",
        content: "Do you have availability this weekend?",
        timestamp: "10:20 AM",
        sentiment: "positive",
      },
    ],
  },
  {
    id: "conv_michael",
    contactName: "Michael Brown",
    contactRole: "Inbound Prospect",
    companyName: "PrimeCare Clinic (Client System)",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    channel: "WhatsApp",
    channelHandle: "+1 (555) 392-1084",
    unreadCount: 2,
    lastMessageSnippet: "Can you tell me more about the package?",
    lastMessageAt: "18 mins ago",
    status: "New",
    aiIntent: "pricing_inquiry",
    aiHandled: true,
    messages: [
      {
        id: "m_m1",
        sender: "lead",
        content: "Hi! Can you tell me more about the package?",
        timestamp: "9:50 AM",
        sentiment: "neutral",
      },
      {
        id: "m_m2",
        sender: "ai_agent",
        content: "Hi Michael! We offer comprehensive health checkup packages with instant digital reports. Are you inquiring for yourself or your family?",
        timestamp: "9:50 AM",
        isAiGenerated: true,
      },
    ],
  },
  {
    id: "conv_emma",
    contactName: "Emma Davis",
    contactRole: "Inbound Buyer",
    companyName: "Veloce Interiors (Client System)",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    channel: "Facebook",
    channelHandle: "emma.davis.fb",
    unreadCount: 0,
    lastMessageSnippet: "I'm interested in booking...",
    lastMessageAt: "42 mins ago",
    status: "Follow-up",
    aiIntent: "demo_request",
    aiHandled: true,
    messages: [
      {
        id: "m_e1",
        sender: "lead",
        content: "I'm interested in booking a consultation for a full home remodel.",
        timestamp: "8:30 AM",
        sentiment: "positive",
      },
      {
        id: "m_e2",
        sender: "ai_agent",
        content: "Wonderful Emma! We'd love to help. Here is our direct booking calendar: nexusai.io/book/veloce",
        timestamp: "8:31 AM",
        isAiGenerated: true,
      },
    ],
  },
  {
    id: "conv_james",
    contactName: "James Wilson",
    contactRole: "Operations Lead",
    companyName: "OmniLogistics (Client System)",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    channel: "Website",
    channelHandle: "Live Chat Widget",
    unreadCount: 1,
    lastMessageSnippet: "Need custom integration for our 12 branch locations.",
    lastMessageAt: "1 hour ago",
    status: "Escalated",
    aiIntent: "objection_handling",
    aiHandled: false,
    messages: [
      {
        id: "m_j1",
        sender: "lead",
        content: "We need custom integration for our 12 branch locations. Can your API support multi-tenant routing?",
        timestamp: "7:45 AM",
        sentiment: "hesitant",
      },
    ],
  },
  {
    id: "conv_david",
    contactName: "David Miller",
    contactRole: "Managing Director",
    companyName: "Apex Solar Commercial",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    channel: "Email",
    channelHandle: "david@apexsolar.example.com",
    unreadCount: 0,
    lastMessageSnippet: "Checking proposal breakdown with CFO today.",
    lastMessageAt: "2 hours ago",
    status: "Proposal",
    aiIntent: "high_intent",
    aiHandled: true,
    messages: [
      {
        id: "m_d1",
        sender: "lead",
        content: "Checking proposal breakdown with CFO today. The ROI projections look compelling.",
        timestamp: "6:20 AM",
        sentiment: "positive",
      },
    ],
  },
];
