import { Lead } from "@/types";

export const mockRecentLeads: Lead[] = [
  {
    id: "lead_sarah",
    fullName: "Sarah Johnson",
    company: "Alpine Grand Hotel (Client)",
    role: "Guest / Prospective Booking",
    email: "sarah.j@travelers.example.com",
    phone: "+1 (555) 728-1920",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    channel: "Instagram",
    status: "Qualified",
    aiQualificationScore: 92,
    estimatedValue: 3400,
    primaryNeed: "Hotel booking (Presidential Suite Anniversary Package)",
    lastContactedAt: "4 mins ago",
    nextFollowUpAt: "Today, 4:30 PM",
    aiSummary: "Confirmed budget and intent for weekend Presidential Suite booking with spa package.",
    tags: ["Hotel booking", "High Intent", "Weekend Stay"],
  },
  {
    id: "lead_michael",
    fullName: "Michael Brown",
    company: "PrimeCare Clinic (Client)",
    role: "Patient / Executive Health",
    email: "michael.b@executivehealth.example.com",
    phone: "+1 (555) 392-1084",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    channel: "WhatsApp",
    status: "New",
    aiQualificationScore: 78,
    estimatedValue: 1200,
    primaryNeed: "Comprehensive Health Checkup Package inquiry",
    lastContactedAt: "18 mins ago",
    nextFollowUpAt: "Tomorrow, 11:00 AM",
    aiSummary: "Requested pricing details for annual family screening package.",
    tags: ["Healthcare", "Inbound WhatsApp"],
  },
  {
    id: "lead_emma",
    fullName: "Emma Davis",
    company: "Veloce Interiors (Client)",
    role: "Homeowner / Remodel Project",
    email: "emma.davis@designlovers.example.com",
    phone: "+1 (555) 849-2019",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    channel: "Facebook",
    status: "Follow-up",
    aiQualificationScore: 85,
    estimatedValue: 18500,
    primaryNeed: "Full residential interior remodel consultation",
    lastContactedAt: "42 mins ago",
    nextFollowUpAt: "Tomorrow, 2:00 PM",
    aiSummary: "Opened consultation calendar link. Follow-up scheduled to confirm date.",
    tags: ["Consultation", "Design Inbound"],
  },
  {
    id: "lead_james",
    fullName: "James Wilson",
    company: "OmniLogistics (Client)",
    role: "Operations Director",
    email: "j.wilson@omnilogistics.example.com",
    phone: "+1 (555) 918-3401",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    channel: "Website",
    status: "Escalated",
    aiQualificationScore: 89,
    estimatedValue: 28000,
    primaryNeed: "Multi-tenant freight routing API across 12 branch locations",
    lastContactedAt: "1 hour ago",
    aiSummary: "Technical SLA inquiry escalated to founder for custom enterprise terms.",
    tags: ["Enterprise API", "High Value"],
  },
  {
    id: "lead_david",
    fullName: "David Miller",
    company: "Apex Solar Commercial",
    role: "Managing Director",
    email: "david@apexsolar.example.com",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    channel: "Email",
    status: "Proposal",
    aiQualificationScore: 94,
    estimatedValue: 36000,
    primaryNeed: "Commercial solar acquisition funnel and automated roof analysis bot",
    lastContactedAt: "2 hours ago",
    aiSummary: "Proposal under CFO review. Positive feedback on projected lead ROI.",
    tags: ["Proposal Active", "CleanTech"],
  },
  {
    id: "lead_priya",
    fullName: "Priya Sharma",
    company: "Catalyst Medical (Client)",
    role: "Client / Laser Aesthetic",
    email: "priya.s@aesthetics.example.com",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    channel: "WhatsApp",
    status: "Won",
    aiQualificationScore: 96,
    estimatedValue: 4800,
    primaryNeed: "Advanced skin rejuvenation 6-session package",
    lastContactedAt: "3 hours ago",
    aiSummary: "Confirmed appointment and deposit paid via WhatsApp booking link.",
    tags: ["Closed Won", "Deposit Paid"],
  },
];
