import { MetricItem } from "@/types";

export interface TimeframeMetrics {
  today: MetricItem[];
  "7days": MetricItem[];
  "30days": MetricItem[];
}

export const mockDashboardMetrics: MetricItem[] = [
  {
    id: "metric_total_leads",
    title: "Total Leads",
    value: "248",
    changePercentage: 12,
    isPositiveChange: true,
    timeframe: "vs. previous period",
    iconName: "HiOutlineUsers",
    accentColor: "blue",
    subtitle: "Inbound across all channels",
  },
  {
    id: "metric_qualified_leads",
    title: "Qualified Leads",
    value: "71",
    changePercentage: 18,
    isPositiveChange: true,
    timeframe: "vs. previous period",
    iconName: "HiOutlineCheckBadge",
    accentColor: "emerald",
    subtitle: "28.6% qualification rate",
  },
  {
    id: "metric_conversations",
    title: "Conversations",
    value: "231",
    changePercentage: 24,
    isPositiveChange: true,
    timeframe: "vs. previous period",
    iconName: "HiOutlineChatBubbleLeftRight",
    accentColor: "violet",
    subtitle: "88% automated replies",
  },
  {
    id: "metric_closed_deals",
    title: "Closed Deals",
    value: "8",
    changePercentage: 33,
    isPositiveChange: true,
    timeframe: "vs. previous period",
    iconName: "HiOutlineBanknotes",
    accentColor: "emerald",
    subtitle: "$48,500 contract value",
  },
];

export const mockTimeframeMetrics: TimeframeMetrics = {
  today: mockDashboardMetrics,
  "7days": [
    {
      id: "metric_total_leads",
      title: "Total Leads",
      value: "842",
      changePercentage: 16,
      isPositiveChange: true,
      timeframe: "vs. previous 7 days",
      iconName: "HiOutlineUsers",
      accentColor: "blue",
      subtitle: "Inbound across all channels",
    },
    {
      id: "metric_qualified_leads",
      title: "Qualified Leads",
      value: "218",
      changePercentage: 21,
      isPositiveChange: true,
      timeframe: "vs. previous 7 days",
      iconName: "HiOutlineCheckBadge",
      accentColor: "emerald",
      subtitle: "25.8% qualification rate",
    },
    {
      id: "metric_conversations",
      title: "Conversations",
      value: "910",
      changePercentage: 29,
      isPositiveChange: true,
      timeframe: "vs. previous 7 days",
      iconName: "HiOutlineChatBubbleLeftRight",
      accentColor: "violet",
      subtitle: "86% automated replies",
    },
    {
      id: "metric_closed_deals",
      title: "Closed Deals",
      value: "23",
      changePercentage: 40,
      isPositiveChange: true,
      timeframe: "vs. previous 7 days",
      iconName: "HiOutlineBanknotes",
      accentColor: "emerald",
      subtitle: "$142,000 contract value",
    },
  ],
  "30days": [
    {
      id: "metric_total_leads",
      title: "Total Leads",
      value: "2,840",
      changePercentage: 28,
      isPositiveChange: true,
      timeframe: "vs. previous 30 days",
      iconName: "HiOutlineUsers",
      accentColor: "blue",
      subtitle: "Inbound across all channels",
    },
    {
      id: "metric_qualified_leads",
      title: "Qualified Leads",
      value: "764",
      changePercentage: 34,
      isPositiveChange: true,
      timeframe: "vs. previous 30 days",
      iconName: "HiOutlineCheckBadge",
      accentColor: "emerald",
      subtitle: "26.9% qualification rate",
    },
    {
      id: "metric_conversations",
      title: "Conversations",
      value: "3,420",
      changePercentage: 38,
      isPositiveChange: true,
      timeframe: "vs. previous 30 days",
      iconName: "HiOutlineChatBubbleLeftRight",
      accentColor: "violet",
      subtitle: "90% automated replies",
    },
    {
      id: "metric_closed_deals",
      title: "Closed Deals",
      value: "64",
      changePercentage: 45,
      isPositiveChange: true,
      timeframe: "vs. previous 30 days",
      iconName: "HiOutlineBanknotes",
      accentColor: "emerald",
      subtitle: "$384,000 contract value",
    },
  ],
};
