import {
  ChannelConfig,
  ChannelIdentity,
  ChannelEvent,
} from "@/lib/channels/types";

// ---------------------------------------------------------------------------
// Initial Channel Configurations across Clients
// ---------------------------------------------------------------------------
export const initialMockChannelConfigs: ChannelConfig[] = [
  // Client 1: ABC International School
  {
    id: "chan_abc_web",
    type: "website",
    name: "Admissions Live Chat Widget",
    description: "Embedded inquiry widget on admissions.abcschool.example.com",
    status: "MOCK",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    accountName: "Main Admissions Portal",
    accountIdentifier: "admissions.abcschool.example.com",
    lastConnectedAt: "2026-03-01T10:00:00Z",
    lastEventAt: "2026-03-29T10:14:00Z",
    unreadCount: 1,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "conversation_history"],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-29T10:14:00Z",
    simulationMode: true,
  },
  {
    id: "chan_abc_wa",
    type: "whatsapp",
    name: "Admissions WhatsApp Desk",
    description: "Official WhatsApp Cloud line for parents & prospect students",
    status: "MOCK",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    accountName: "ABC School Helpdesk",
    accountIdentifier: "+91 94190 12345",
    lastConnectedAt: "2026-03-05T12:00:00Z",
    lastEventAt: "2026-03-29T09:30:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "quick_replies", "conversation_history"],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-29T09:30:00Z",
    simulationMode: true,
  },
  {
    id: "chan_abc_ig",
    type: "instagram",
    name: "Instagram Direct Admissions",
    description: "Direct message lead qualification from school's Instagram profile",
    status: "NEEDS_SETUP",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    accountName: "@abcschool_official",
    accountIdentifier: "@abcschool_official",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support"],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_abc_email",
    type: "email",
    name: "Admissions Office Email Relay",
    description: "Inbound mailbox routing for admissions@abcschool.example.com",
    status: "MOCK",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    accountName: "Admissions Inbox",
    accountIdentifier: "admissions@abcschool.example.com",
    lastConnectedAt: "2026-03-01T10:00:00Z",
    lastEventAt: "2026-03-29T08:00:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "conversation_history"],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-29T08:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_abc_fb",
    type: "facebook",
    name: "Facebook Admissions Messenger",
    description: "Messenger integration on school's official Facebook Page",
    status: "NEEDS_SETUP",
    clientId: "client_abc_school",
    clientName: "ABC International School",
    accountName: "ABC International School Official",
    accountIdentifier: "fb.me/abcschoolofficial",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support"],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
    simulationMode: true,
  },

  // Client 2: Alpine Grand Resort & Spa
  {
    id: "chan_alp_web",
    type: "website",
    name: "Concierge Direct Booking Chat",
    description: "Live guest booking widget on alpinegrand.example.com",
    status: "MOCK",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    accountName: "Alpine Web Concierge",
    accountIdentifier: "book.alpinegrand.example.com",
    lastConnectedAt: "2026-03-10T09:00:00Z",
    lastEventAt: "2026-03-29T11:45:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "attachments"],
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-29T11:45:00Z",
    simulationMode: true,
  },
  {
    id: "chan_alp_ig",
    type: "instagram",
    name: "Instagram Luxury Concierge",
    description: "Story replies and DM booking intake from @alpinegrand_resort",
    status: "MOCK",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    accountName: "@alpinegrand_resort",
    accountIdentifier: "@alpinegrand_resort",
    lastConnectedAt: "2026-03-12T14:00:00Z",
    lastEventAt: "2026-03-29T08:30:00Z",
    unreadCount: 2,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "quick_replies"],
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-29T08:30:00Z",
    simulationMode: true,
  },
  {
    id: "chan_alp_wa",
    type: "whatsapp",
    name: "WhatsApp VIP Concierge",
    description: "Direct guest reservations & room service chat",
    status: "MOCK",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    accountName: "Alpine Guest Care",
    accountIdentifier: "+91 94191 55667",
    lastConnectedAt: "2026-03-15T11:00:00Z",
    lastEventAt: "2026-03-29T10:00:00Z",
    unreadCount: 1,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "attachments", "quick_replies"],
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-29T10:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_alp_email",
    type: "email",
    name: "Reservations Mailbox",
    description: "Inbound reservations email relay",
    status: "MOCK",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    accountName: "Reservations Desk",
    accountIdentifier: "stay@alpinegrand.example.com",
    lastConnectedAt: "2026-03-10T09:00:00Z",
    lastEventAt: "2026-03-28T14:00:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture"],
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-28T14:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_alp_fb",
    type: "facebook",
    name: "Facebook Messenger Page",
    description: "Guest inquiries from Alpine Grand Facebook page",
    status: "NEEDS_SETUP",
    clientId: "client_alpine_hotel",
    clientName: "Alpine Grand Resort & Spa",
    accountName: "Alpine Grand Resort",
    accountIdentifier: "fb.me/alpinegrandgulmarg",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support"],
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
    simulationMode: true,
  },

  // Client 3: PrimeCare Clinic
  {
    id: "chan_pc_wa",
    type: "whatsapp",
    name: "Clinic OPD Appointments WhatsApp",
    description: "Automated triage & patient slot reservation line",
    status: "MOCK",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    accountName: "PrimeCare Desk",
    accountIdentifier: "+91 98110 00199",
    lastConnectedAt: "2026-03-18T10:00:00Z",
    lastEventAt: "2026-03-29T11:00:00Z",
    unreadCount: 1,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support", "quick_replies"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-29T11:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_pc_web",
    type: "website",
    name: "Patient Triage Web Bot",
    description: "Symptom check and doctor consultation scheduler",
    status: "MOCK",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    accountName: "PrimeCare Portal",
    accountIdentifier: "care.primecareclinic.example.com",
    lastConnectedAt: "2026-03-18T10:00:00Z",
    lastEventAt: "2026-03-29T09:15:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture", "ai_support"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-29T09:15:00Z",
    simulationMode: true,
  },
  {
    id: "chan_pc_ig",
    type: "instagram",
    name: "Instagram Health Q&A",
    description: "Doctor DM answers & wellness package promotions",
    status: "NEEDS_SETUP",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    accountName: "@primecare_delhi",
    accountIdentifier: "@primecare_delhi",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_pc_email",
    type: "email",
    name: "Doctor Referrals Inbox",
    description: "Medical report intake & appointment desk",
    status: "MOCK",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    accountName: "Appointments Inbox",
    accountIdentifier: "appointments@primecareclinic.example.com",
    lastConnectedAt: "2026-03-18T10:00:00Z",
    lastEventAt: "2026-03-27T16:00:00Z",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-27T16:00:00Z",
    simulationMode: true,
  },
  {
    id: "chan_pc_fb",
    type: "facebook",
    name: "Facebook Clinic Page",
    description: "Clinic timings & reviews Messenger intake",
    status: "NEEDS_SETUP",
    clientId: "client_primecare_clinic",
    clientName: "PrimeCare Multi-Specialty Clinic",
    accountName: "PrimeCare Clinic South Extension",
    accountIdentifier: "fb.me/primecaredelhi",
    unreadCount: 0,
    capabilities: ["receive_messages", "send_messages", "lead_capture"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
    simulationMode: true,
  },
];

// ---------------------------------------------------------------------------
// Channel Identities (Multi-channel identity mapping per lead)
// Demonstrates cross-channel identity unification!
// ---------------------------------------------------------------------------
export const initialMockIdentities: ChannelIdentity[] = [
  // Ayaan Khan: Cross-channel demonstration hero!
  // Same Lead with Instagram + WhatsApp + Email + Website identities
  {
    id: "idnt_ayaan_ig",
    clientId: "client_alpine_hotel",
    leadId: "lead_ayaan_khan",
    channelType: "instagram",
    externalUserId: "ig_u_94829104",
    identifier: "@ayaan_demo",
    displayName: "Ayaan Khan",
    metadata: {
      profileUrl: "https://instagram.com/ayaan_demo",
      device: "Instagram for iOS",
    },
    firstSeenAt: "2026-03-27T11:00:00Z",
    lastSeenAt: "2026-03-27T11:45:00Z",
  },
  {
    id: "idnt_ayaan_wa",
    clientId: "client_alpine_hotel",
    leadId: "lead_ayaan_khan",
    channelType: "whatsapp",
    externalUserId: "919876543210",
    identifier: "+91 98765 43210",
    displayName: "Ayaan Khan (Verified WA)",
    metadata: {
      phone: "+91 98765 43210",
    },
    firstSeenAt: "2026-03-28T09:30:00Z",
    lastSeenAt: "2026-03-29T10:15:00Z",
  },
  {
    id: "idnt_ayaan_em",
    clientId: "client_alpine_hotel",
    leadId: "lead_ayaan_khan",
    channelType: "email",
    externalUserId: "ayaan@example.com",
    identifier: "ayaan@example.com",
    displayName: "Ayaan Khan",
    metadata: {
      email: "ayaan@example.com",
    },
    firstSeenAt: "2026-03-28T14:20:00Z",
    lastSeenAt: "2026-03-28T14:20:00Z",
  },
  {
    id: "idnt_ayaan_web",
    clientId: "client_alpine_hotel",
    leadId: "lead_ayaan_khan",
    channelType: "website",
    externalUserId: "sess_web_83921",
    identifier: "Session #83921 (Gulmarg Booking)",
    displayName: "Ayaan Khan",
    metadata: {
      ipCountry: "India",
      device: "macOS Chrome",
    },
    firstSeenAt: "2026-03-29T11:00:00Z",
    lastSeenAt: "2026-03-29T11:30:00Z",
  },

  // Rahul Sharma: Website Chat + Phone
  {
    id: "idnt_rahul_web",
    clientId: "client_abc_school",
    leadId: "lead_rahul_sharma",
    channelType: "website",
    externalUserId: "sess_rahul_99120",
    identifier: "Session #99120 (Admissions Portal)",
    displayName: "Rahul Sharma",
    firstSeenAt: "2026-03-28T10:14:00Z",
    lastSeenAt: "2026-03-29T11:30:00Z",
  },
  {
    id: "idnt_rahul_wa",
    clientId: "client_abc_school",
    leadId: "lead_rahul_sharma",
    channelType: "whatsapp",
    externalUserId: "919876543210",
    identifier: "+91 98765 43210",
    displayName: "Rahul Sharma (Parent)",
    firstSeenAt: "2026-03-29T09:00:00Z",
    lastSeenAt: "2026-03-29T10:00:00Z",
  },

  // Sarah Johnson: Instagram + Email
  {
    id: "idnt_sarah_ig",
    clientId: "client_alpine_hotel",
    leadId: "lead_sarah_johnson",
    channelType: "instagram",
    externalUserId: "ig_u_sarahj_travel",
    identifier: "@sarahj_travels",
    displayName: "Sarah Johnson",
    firstSeenAt: "2026-03-29T08:30:00Z",
    lastSeenAt: "2026-03-29T09:15:00Z",
  },

  // Michael Brown: WhatsApp
  {
    id: "idnt_michael_wa",
    clientId: "client_primecare_clinic",
    leadId: "lead_michael_brown",
    channelType: "whatsapp",
    externalUserId: "919811234567",
    identifier: "+91 98112 34567",
    displayName: "Michael Brown",
    firstSeenAt: "2026-03-29T11:00:00Z",
    lastSeenAt: "2026-03-29T11:20:00Z",
  },
];

// ---------------------------------------------------------------------------
// Initial Normalized Channel Events (Event Log & Idempotency Audit Trail)
// Includes PROCESSED, DUPLICATE (idempotency prevented), and FAILED (for retry test)
// ---------------------------------------------------------------------------
export const initialMockChannelEvents: ChannelEvent[] = [
  // 1. Processed WhatsApp Message
  {
    id: "ev_wa_101",
    clientId: "client_alpine_hotel",
    channelId: "chan_alp_wa",
    channelType: "whatsapp",
    externalEventId: "wamid_demo_99210_evt",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_ayaan_wa",
    leadId: "lead_ayaan_khan",
    direction: "INBOUND",
    payload: {
      object: "whatsapp_business_account",
      entry: [
        {
          changes: [
            {
              field: "messages",
              value: {
                messages: [{ from: "919876543210", text: { body: "I want to confirm the presidential suite booking for this weekend." } }],
              },
            },
          ],
        },
      ],
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "wamid_demo_99210_evt",
      externalMessageId: "wamid.HBgL99210",
      externalSenderId: "919876543210",
      senderName: "Ayaan Khan",
      senderContact: { phone: "+91 98765 43210" },
      channelType: "whatsapp",
      text: "I want to confirm the presidential suite booking for this weekend.",
      timestamp: "2026-03-29T10:15:00Z",
      rawSource: "Meta WhatsApp Cloud API Webhook (Simulated)",
    },
    status: "PROCESSED",
    receivedAt: "2026-03-29T10:15:00Z",
    processedAt: "2026-03-29T10:15:01Z",
    retryCount: 0,
  },

  // 2. Duplicate Event — Idempotency Protection In Action!
  {
    id: "ev_wa_102_dup",
    clientId: "client_alpine_hotel",
    channelId: "chan_alp_wa",
    channelType: "whatsapp",
    externalEventId: "wamid_demo_99210_evt", // Exact match with event #1!
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_ayaan_wa",
    leadId: "lead_ayaan_khan",
    direction: "INBOUND",
    payload: {
      object: "whatsapp_business_account",
      note: "Retried delivery by webhook service",
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "wamid_demo_99210_evt",
      externalSenderId: "919876543210",
      senderName: "Ayaan Khan",
      channelType: "whatsapp",
      text: "I want to confirm the presidential suite booking for this weekend.",
      timestamp: "2026-03-29T10:15:05Z",
      rawSource: "Meta WhatsApp Cloud API Webhook (Simulated)",
    },
    status: "DUPLICATE",
    receivedAt: "2026-03-29T10:15:05Z",
    processedAt: "2026-03-29T10:15:05Z",
    error: "Duplicate event ignored: Event with matching idempotency key (client_alpine_hotel:whatsapp:wamid_demo_99210_evt) already processed.",
    retryCount: 0,
  },

  // 3. Simulated Failed Event — Ready for User to Test Retry Flow!
  {
    id: "ev_ig_failed_103",
    clientId: "client_alpine_hotel",
    channelId: "chan_alp_ig",
    channelType: "instagram",
    externalEventId: "ig_mid_err_7718",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_sarah_alpine",
    leadId: "lead_sarah_johnson",
    direction: "INBOUND",
    payload: {
      object: "instagram",
      entry: [{ messaging: [{ message: { text: "Can you send the spa menu PDF directly?" } }] }],
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "ig_mid_err_7718",
      externalSenderId: "ig_u_sarahj_travel",
      senderName: "Sarah Johnson",
      channelType: "instagram",
      text: "Can you send the spa menu PDF directly?",
      timestamp: "2026-03-29T08:45:00Z",
      rawSource: "Meta Instagram Graph Webhook (Simulated)",
    },
    status: "FAILED",
    receivedAt: "2026-03-29T08:45:00Z",
    error: "Processing failed: Meta Graph API Rate Limit exceeded (Simulated webhook delivery error). Retry available.",
    retryCount: 0,
  },

  // 4. Inbound Website Message Processed
  {
    id: "ev_web_104",
    clientId: "client_abc_school",
    channelId: "chan_abc_web",
    channelType: "website",
    externalEventId: "web_evt_rahul_101",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_rahul_abc",
    leadId: "lead_rahul_sharma",
    direction: "INBOUND",
    payload: {
      event: "widget.message.created",
      visitor: { name: "Rahul Sharma", email: "rahul.sharma@familymail.example.com" },
      body: "We relocated to Srinagar and would like Grade 8 syllabus details.",
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "web_evt_rahul_101",
      externalSenderId: "sess_rahul_99120",
      senderName: "Rahul Sharma",
      senderContact: { email: "rahul.sharma@familymail.example.com" },
      channelType: "website",
      text: "We relocated to Srinagar and would like Grade 8 syllabus details.",
      timestamp: "2026-03-28T10:14:00Z",
      rawSource: "Website Chat Widget Webhook (Simulated)",
    },
    status: "PROCESSED",
    receivedAt: "2026-03-28T10:14:00Z",
    processedAt: "2026-03-28T10:14:01Z",
    retryCount: 0,
  },

  // 5. Inbound Instagram DM Processed
  {
    id: "ev_ig_105",
    clientId: "client_alpine_hotel",
    channelId: "chan_alp_ig",
    channelType: "instagram",
    externalEventId: "ig_mid_ayaan_start",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_ayaan_ig",
    leadId: "lead_ayaan_khan",
    direction: "INBOUND",
    payload: {
      object: "instagram",
      entry: [{ messaging: [{ message: { text: "Hi, what are your presidential suite prices for this month?" } }] }],
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "ig_mid_ayaan_start",
      externalSenderId: "ig_u_94829104",
      senderName: "Ayaan Khan",
      senderContact: { handle: "@ayaan_demo" },
      channelType: "instagram",
      text: "Hi, what are your presidential suite prices for this month?",
      timestamp: "2026-03-27T11:00:00Z",
      rawSource: "Meta Instagram Graph Webhook (Simulated)",
    },
    status: "PROCESSED",
    receivedAt: "2026-03-27T11:00:00Z",
    processedAt: "2026-03-27T11:00:01Z",
    retryCount: 0,
  },

  // 6. Inbound Email Relay Processed
  {
    id: "ev_em_106",
    clientId: "client_abc_school",
    channelId: "chan_abc_email",
    channelType: "email",
    externalEventId: "em_ses_msg_9901",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_email_inquiry_abc",
    leadId: "lead_dr_sana_mir",
    direction: "INBOUND",
    payload: {
      event: "email.received",
      mail: { source: "sana.mir@healthkashmir.org", commonHeaders: { subject: "Admission query for Grade 5 & Transportation routes" } },
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "em_ses_msg_9901",
      externalSenderId: "sana.mir@healthkashmir.org",
      senderName: "Dr. Sana Mir",
      senderContact: { email: "sana.mir@healthkashmir.org" },
      channelType: "email",
      text: "Hello admissions office, inquiring about Grade 5 transfer admissions and morning school bus pick-up routes from Nishat area.",
      timestamp: "2026-03-29T08:00:00Z",
      rawSource: "Inbound Email SMTP Relay (Simulated)",
    },
    status: "PROCESSED",
    receivedAt: "2026-03-29T08:00:00Z",
    processedAt: "2026-03-29T08:00:02Z",
    retryCount: 0,
  },

  // 7. Inbound Facebook Messenger Processed
  {
    id: "ev_fb_107",
    clientId: "client_veloce_interiors",
    channelId: "chan_fb_veloce",
    channelType: "facebook",
    externalEventId: "fb_msg_mid_22891",
    eventType: "MESSAGE_RECEIVED",
    conversationId: "conv_emma_veloce",
    leadId: "lead_emma_davis",
    direction: "INBOUND",
    payload: {
      object: "page",
      entry: [{ messaging: [{ message: { text: "Do you have interior portfolio brochures for 4BHK apartments in Bandra?" } }] }],
      simulation_flag: true,
    },
    normalizedPayload: {
      externalEventId: "fb_msg_mid_22891",
      externalSenderId: "fb_user_emma_d",
      senderName: "Emma Davis",
      channelType: "facebook",
      text: "Do you have interior portfolio brochures for 4BHK apartments in Bandra?",
      timestamp: "2026-03-27T14:00:00Z",
      rawSource: "Meta Messenger Webhook (Simulated)",
    },
    status: "PROCESSED",
    receivedAt: "2026-03-27T14:00:00Z",
    processedAt: "2026-03-27T14:00:01Z",
    retryCount: 0,
  },
];
