import {
  FollowUp,
  AutomationRule,
  MessageTemplate,
  AutomationRun,
  FollowUpSuggestion,
} from "./types";

export const initialMockMessageTemplates: MessageTemplate[] = [
  {
    id: "tpl_lead_no_reply_whatsapp",
    name: "Client Lead — WhatsApp Gentle Check-in",
    targetType: "LEAD",
    category: "No-Reply Nudge",
    channel: "whatsapp",
    body: "Hi {{lead.first_name}}! Just checking back from {{client.name}} regarding your recent inquiry. Would you still like us to hold availability for you?",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-01T10:00:00Z",
  },
  {
    id: "tpl_lead_no_reply_instagram",
    name: "Client Lead — Instagram DM Nudge",
    targetType: "LEAD",
    category: "No-Reply Nudge",
    channel: "instagram",
    body: "Hey {{lead.first_name}} 👋 We saw your message about booking at {{client.name}}. Let us know if you need any assistance choosing the right option!",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-01T11:00:00Z",
  },
  {
    id: "tpl_lead_appt_reminder_whatsapp",
    name: "Client Lead — Appointment 2h Reminder",
    targetType: "LEAD",
    category: "Appointment & Reminders",
    channel: "whatsapp",
    body: "Hi {{lead.first_name}}, friendly reminder that your appointment with {{client.name}} is set for {{appointment.date}} at {{appointment.time}}. Reply 1 to confirm or 2 to reschedule.",
    variables: ["lead.first_name", "client.name", "appointment.date", "appointment.time"],
    isSystemDefault: true,
    updatedAt: "2026-10-01T12:00:00Z",
  },
  {
    id: "tpl_lead_vip_quote_whatsapp",
    name: "Client Lead — VIP Quote Expiration Alert",
    targetType: "LEAD",
    category: "VIP & Objections",
    channel: "whatsapp",
    body: "Hi {{lead.first_name}}, {{agent.name}} here from {{client.name}}. The special seasonal rate we quoted is valid until {{offer.expiration_date}}. Can I finalize your reservation today?",
    variables: ["lead.first_name", "agent.name", "client.name", "offer.expiration_date"],
    isSystemDefault: true,
    updatedAt: "2026-10-01T13:30:00Z",
  },
  {
    id: "tpl_lead_email_reengagement",
    name: "Client Lead — 14-Day Re-engagement Email",
    targetType: "LEAD",
    category: "Re-engagement",
    channel: "email",
    subject: "Still exploring options with {{client.name}}?",
    body: "Hi {{lead.first_name}},\n\nWe noticed you explored our services two weeks ago. If you still have questions or need a tailored package, we would love to help!\n\nBest regards,\n{{client.name}} Team",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-01T14:00:00Z",
  },
  {
    id: "tpl_prospect_demo_ready_email",
    name: "Nexus Prospect — Interactive AI Demo Invitation",
    targetType: "PROSPECT",
    category: "Demo & Proposal",
    channel: "email",
    subject: "Custom AI Concierge built for {{prospect.name}}",
    body: "Hi {{prospect.contact}},\n\nWe analyzed {{prospect.name}}'s inbound lead flow in {{prospect.industry}} and built a functioning AI lead-capture prototype.\n\nYou can test it interactively here: {{demo.link}}\n\nWould you have 10 minutes this week to review the revenue impact?\n\nBest,\n{{agent.name}}\nNEXUS AI",
    variables: ["prospect.contact", "prospect.name", "prospect.industry", "demo.link", "agent.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T09:00:00Z",
  },
  {
    id: "tpl_prospect_whatsapp_quick_demo",
    name: "Nexus Prospect — WhatsApp Prototype Link",
    targetType: "PROSPECT",
    category: "Demo & Proposal",
    channel: "whatsapp",
    body: "Hello {{prospect.contact}}, Kumail from NEXUS AI. We generated an automated 24/7 client booking prototype specifically for {{prospect.name}}. View the live demo: {{demo.link}}. Let me know what you think!",
    variables: ["prospect.contact", "prospect.name", "demo.link"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T10:00:00Z",
  },
  {
    id: "tpl_prospect_proposal_checkin",
    name: "Nexus Prospect — Proposal Review Check-in",
    targetType: "PROSPECT",
    category: "Demo & Proposal",
    channel: "email",
    subject: "Quick question on our NEXUS AI proposal for {{prospect.name}}",
    body: "Hi {{prospect.contact}},\n\nFollowing up on the proposal sent for {{prospect.name}}. Did your executive team have a chance to review the multi-channel integration timeline?\n\nHappy to hop on a quick call if you need any adjustments.\n\nWarmly,\n{{agent.name}}",
    variables: ["prospect.contact", "prospect.name", "agent.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T11:00:00Z",
  },
  {
    id: "tpl_prospect_instagram_dm_hook",
    name: "Nexus Prospect — Instagram Audit Hook",
    targetType: "PROSPECT",
    category: "No-Reply Nudge",
    channel: "instagram",
    body: "Hi {{prospect.name}} team! We noticed high engagement on your recent posts but found delayed responses to direct booking inquiries. We built an AI system for {{prospect.industry}} brands that answers instantly. Open to a 3-minute video?",
    variables: ["prospect.name", "prospect.industry"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T12:00:00Z",
  },
  {
    id: "tpl_lead_fb_messenger_nudge",
    name: "Client Lead — Facebook Messenger Follow-Up",
    targetType: "LEAD",
    category: "No-Reply Nudge",
    channel: "facebook",
    body: "Hi {{lead.first_name}}! Thanks for contacting {{client.name}} on Facebook. Our team is ready to assist you. Do you have any questions about our pricing or availability?",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T13:00:00Z",
  },
  {
    id: "tpl_lead_quote_followup_email",
    name: "Client Lead — Quote Sent Follow-Up",
    targetType: "LEAD",
    category: "VIP & Objections",
    channel: "email",
    subject: "Your personalized quote from {{client.name}}",
    body: "Hello {{lead.first_name}},\n\nFollowing up on the quote we prepared for you. Please let us know if you would like any modifications before we finalize your schedule.\n\nSincerely,\n{{client.name}}",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T14:00:00Z",
  },
  {
    id: "tpl_prospect_cold_nudge_email",
    name: "Nexus Prospect — Post-Demo 48h Follow-Up",
    targetType: "PROSPECT",
    category: "Re-engagement",
    channel: "email",
    subject: "Next steps for {{prospect.name}} AI Deployment",
    body: "Hi {{prospect.contact}},\n\nHope you had a chance to test the AI demo we configured for {{prospect.name}}. Based on your current lead volume, the projected monthly recovered revenue is significant.\n\nShould we schedule a 15-minute onboarding walkthrough?\n\nBest,\n{{agent.name}}",
    variables: ["prospect.contact", "prospect.name", "agent.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T15:00:00Z",
  },
  {
    id: "tpl_lead_satisfaction_checkin",
    name: "Client Lead — Post-Service Feedback",
    targetType: "LEAD",
    category: "Appointment & Reminders",
    channel: "whatsapp",
    body: "Hi {{lead.first_name}}, thank you for choosing {{client.name}}! On a scale of 1-5, how was your experience with our team today?",
    variables: ["lead.first_name", "client.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "tpl_lead_website_live_nudge",
    name: "Client Lead — Website Chat Re-engagement",
    targetType: "LEAD",
    category: "No-Reply Nudge",
    channel: "website",
    body: "Hi {{lead.first_name}}, we noticed you paused the conversation. If you still have questions, I'm here to help right now!",
    variables: ["lead.first_name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T17:00:00Z",
  },
  {
    id: "tpl_prospect_reengagement_quarterly",
    name: "Nexus Prospect — Quarterly Follow-Up Check",
    targetType: "PROSPECT",
    category: "Re-engagement",
    channel: "email",
    subject: "Quick check-in regarding {{prospect.name}}",
    body: "Hi {{prospect.contact}},\n\nReaching back out to see how your client acquisition and response rates are progressing this quarter at {{prospect.name}}. We've recently rolled out new WhatsApp automation capabilities that might interest you.\n\nBest,\n{{agent.name}}",
    variables: ["prospect.contact", "prospect.name", "agent.name"],
    isSystemDefault: true,
    updatedAt: "2026-10-02T18:00:00Z",
  },
];

export const initialMockAutomationRules: AutomationRule[] = [
  {
    id: "rule_lead_2h_whatsapp_nudge",
    name: "Client Lead — 2-Hour No Reply Nudge (WhatsApp)",
    description: "Automatically nudges qualified client leads who stop responding after initial quote inquiry.",
    targetType: "LEAD",
    category: "Client Lead Capture",
    enabled: true,
    trigger: {
      type: "NO_REPLY_HOURS",
      delayMinutes: 120,
    },
    conditions: [
      { field: "channel", operator: "equals", value: "whatsapp" },
      { field: "qualification_score", operator: "greater_than", value: 60 },
      { field: "has_human_takeover", operator: "equals", value: false },
    ],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "NO_REPLY_NUDGE",
      channel: "whatsapp",
      templateId: "tpl_lead_no_reply_whatsapp",
      automationMode: "AUTONOMOUS",
      priority: "HIGH",
      delayHours: 2,
    },
    createdAt: "2026-10-01T08:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z",
    runsCount: 48,
    successCount: 46,
  },
  {
    id: "rule_lead_instagram_inactivity",
    name: "Client Lead — Instagram 4-Hour Re-engagement",
    description: "Sends an Instagram DM nudge when a visitor asks about pricing but goes inactive.",
    targetType: "LEAD",
    category: "Client Lead Capture",
    enabled: true,
    trigger: {
      type: "NO_REPLY_HOURS",
      delayMinutes: 240,
    },
    conditions: [
      { field: "channel", operator: "equals", value: "instagram" },
      { field: "has_human_takeover", operator: "equals", value: false },
    ],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "NO_REPLY_NUDGE",
      channel: "instagram",
      templateId: "tpl_lead_no_reply_instagram",
      automationMode: "AUTONOMOUS",
      priority: "MEDIUM",
      delayHours: 4,
    },
    createdAt: "2026-10-01T09:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z",
    runsCount: 32,
    successCount: 31,
  },
  {
    id: "rule_lead_appt_reminder_24h",
    name: "Client Lead — 24-Hour Appointment Confirmation",
    description: "Schedules automated appointment reminder 24 hours prior to booked consultation.",
    targetType: "LEAD",
    category: "Client Lead Capture",
    enabled: true,
    trigger: {
      type: "APPOINTMENT_UPCOMING",
      delayMinutes: 1440,
    },
    conditions: [{ field: "has_appointment", operator: "equals", value: true }],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "POST_BOOKING_REMINDER",
      channel: "whatsapp",
      templateId: "tpl_lead_appt_reminder_whatsapp",
      automationMode: "AUTONOMOUS",
      priority: "URGENT",
      delayHours: 24,
    },
    createdAt: "2026-10-01T10:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z",
    runsCount: 65,
    successCount: 65,
  },
  {
    id: "rule_lead_human_handoff_pause",
    name: "Safety Rule — Pause Automated Follow-ups on Human Takeover",
    description: "Instantly suspends AI follow-ups whenever a human staff member takes over the lead chat.",
    targetType: "LEAD",
    category: "Omnichannel Handoff",
    enabled: true,
    trigger: {
      type: "HUMAN_HANDOFF_ACTIVATED",
    },
    conditions: [{ field: "has_human_takeover", operator: "equals", value: true }],
    action: {
      type: "PAUSE_EXISTING_FOLLOW_UPS",
      automationMode: "AUTONOMOUS",
      priority: "URGENT",
    },
    createdAt: "2026-10-01T10:30:00Z",
    updatedAt: "2026-10-02T10:00:00Z",
    runsCount: 14,
    successCount: 14,
  },
  {
    id: "rule_prospect_demo_ready_email",
    name: "Nexus Prospect — Auto-Dispatch AI Demo Preview",
    description: "Dispatches customized interactive AI demo link when a prospect moves to DEMO READY.",
    targetType: "PROSPECT",
    category: "Prospect Acquisition",
    enabled: true,
    trigger: {
      type: "PROSPECT_STATUS_CHANGED",
    },
    conditions: [
      { field: "status", operator: "equals", value: "DEMO READY" },
      { field: "has_email", operator: "equals", value: true },
    ],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "DEMO_PREPARATION",
      channel: "email",
      templateId: "tpl_prospect_demo_ready_email",
      automationMode: "MANUAL_APPROVAL",
      priority: "HIGH",
      delayHours: 1,
    },
    createdAt: "2026-10-01T11:00:00Z",
    updatedAt: "2026-10-02T12:00:00Z",
    runsCount: 22,
    successCount: 21,
  },
  {
    id: "rule_prospect_proposal_48h_nudge",
    name: "Nexus Prospect — 48h Post-Proposal Check-in",
    description: "Schedules gentle executive check-in 48 hours after proposal submission.",
    targetType: "PROSPECT",
    category: "Prospect Acquisition",
    enabled: true,
    trigger: {
      type: "PROSPECT_STATUS_CHANGED",
    },
    conditions: [{ field: "status", operator: "equals", value: "PROPOSAL" }],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "NO_REPLY_NUDGE",
      channel: "email",
      templateId: "tpl_prospect_proposal_checkin",
      automationMode: "MANUAL_APPROVAL",
      priority: "HIGH",
      delayHours: 48,
    },
    createdAt: "2026-10-01T12:00:00Z",
    updatedAt: "2026-10-02T12:00:00Z",
    runsCount: 19,
    successCount: 18,
  },
  {
    id: "rule_lead_vip_quote_expiration",
    name: "Client Lead — Quote Expiration Warning",
    description: "Triggers 6 hours before custom room or service quote rate lock expires.",
    targetType: "LEAD",
    category: "Client Lead Capture",
    enabled: true,
    trigger: {
      type: "QUOTE_SENT",
      delayMinutes: 1080,
    },
    conditions: [{ field: "qualification_score", operator: "greater_than", value: 80 }],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "QUOTE_EXCLUSIVITY_EXPIRATION",
      channel: "whatsapp",
      templateId: "tpl_lead_vip_quote_whatsapp",
      automationMode: "MANUAL_APPROVAL",
      priority: "HIGH",
      delayHours: 18,
    },
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-02T14:00:00Z",
    runsCount: 11,
    successCount: 11,
  },
  {
    id: "rule_prospect_whatsapp_hot_lead",
    name: "Nexus Prospect — Hot Prospect WhatsApp Follow-Up",
    description: "Triggers direct WhatsApp message when prospect has high estimated value >$5,000.",
    targetType: "PROSPECT",
    category: "Prospect Acquisition",
    enabled: true,
    trigger: {
      type: "PROSPECT_STATUS_CHANGED",
    },
    conditions: [
      { field: "status", operator: "equals", value: "QUALIFIED" },
      { field: "estimated_deal_value", operator: "greater_than", value: 5000 },
    ],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "DEMO_PREPARATION",
      channel: "whatsapp",
      templateId: "tpl_prospect_whatsapp_quick_demo",
      automationMode: "MANUAL_APPROVAL",
      priority: "URGENT",
      delayHours: 2,
    },
    createdAt: "2026-10-01T15:00:00Z",
    updatedAt: "2026-10-02T15:00:00Z",
    runsCount: 8,
    successCount: 8,
  },
  {
    id: "rule_lead_cold_nurture_14d",
    name: "Client Lead — 14-Day Dormant Re-engagement",
    description: "Re-engages dormant leads that never booked or cancelled over 14 days ago.",
    targetType: "LEAD",
    category: "Re-engagement",
    enabled: true,
    trigger: {
      type: "NO_REPLY_HOURS",
      delayMinutes: 20160,
    },
    conditions: [{ field: "status", operator: "equals", value: "DORMANT" }],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "RE_ENGAGEMENT",
      channel: "email",
      templateId: "tpl_lead_email_reengagement",
      automationMode: "AUTONOMOUS",
      priority: "LOW",
      delayHours: 336,
    },
    createdAt: "2026-10-01T16:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
    runsCount: 29,
    successCount: 28,
  },
  {
    id: "rule_lead_post_service_feedback",
    name: "Client Lead — Post-Service Feedback Check-In",
    targetType: "LEAD",
    category: "Client Lead Capture",
    description: "Requests 1-5 rating 3 hours after a confirmed reservation or service delivery.",
    enabled: true,
    trigger: {
      type: "LEAD_QUALIFIED",
      delayMinutes: 180,
    },
    conditions: [{ field: "status", operator: "equals", value: "CONVERTED" }],
    action: {
      type: "SCHEDULE_FOLLOW_UP",
      followUpType: "FEEDBACK_CHECKIN",
      channel: "whatsapp",
      templateId: "tpl_lead_satisfaction_checkin",
      automationMode: "AUTONOMOUS",
      priority: "MEDIUM",
      delayHours: 3,
    },
    createdAt: "2026-10-01T17:00:00Z",
    updatedAt: "2026-10-02T17:00:00Z",
    runsCount: 42,
    successCount: 42,
  },
];

export const initialMockFollowUps: FollowUp[] = [
  // 1. LEAD: Sarah Johnson - Due Today (WhatsApp)
  {
    id: "fu_lead_sarah_01",
    targetType: "LEAD",
    targetId: "lead_sarah",
    targetName: "Sarah Johnson",
    targetSubtext: "Alpine Grand Hotel (Client Lead)",
    clientId: "client_hotel_alpine",
    clientName: "Alpine Grand Hotel",
    type: "QUOTE_EXCLUSIVITY_EXPIRATION",
    priority: "URGENT",
    channel: "whatsapp",
    status: "DUE",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T09:30:00Z",
    dueAt: "2026-10-03T10:00:00Z",
    triggerReason: "Presidential Suite hold expires at 5:00 PM today. Lead inactive for 2h.",
    templateId: "tpl_lead_vip_quote_whatsapp",
    message: "Hi Sarah! Just checking in — we have one remaining Presidential Suite available for this weekend at Alpine Grand Hotel. Would you like me to hold it for you?",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_01",
        timestamp: "2026-10-03T09:30:00Z",
        action: "Scheduled automatically",
        note: "Triggered by Rule: Quote Expiration Warning",
        performedBy: "NEXUS AI System",
      },
      {
        id: "h_02",
        timestamp: "2026-10-03T10:00:00Z",
        action: "Marked as DUE",
        note: "Queue ready for dispatch",
        performedBy: "Scheduler Worker",
      },
    ],
    createdAt: "2026-10-03T09:30:00Z",
    updatedAt: "2026-10-03T10:00:00Z",
  },

  // 2. LEAD: James Wilson - Due Today (Website / Email)
  {
    id: "fu_lead_james_01",
    targetType: "LEAD",
    targetId: "lead_james",
    targetName: "James Wilson",
    targetSubtext: "OmniLogistics (Client Lead)",
    clientId: "client_omnilogistics",
    clientName: "OmniLogistics",
    type: "NO_REPLY_NUDGE",
    priority: "HIGH",
    channel: "email",
    status: "SCHEDULED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-03T11:00:00Z",
    dueAt: "2026-10-03T11:30:00Z",
    triggerReason: "Requested enterprise tier SLA spec, no interaction for 18 hours.",
    templateId: "tpl_lead_quote_followup_email",
    subject: "OmniLogistics Enterprise Integration SLA Spec",
    message: "Hi James, Kumail reviewed the 12-branch multi-tenant routing terms for OmniLogistics. We've prepared a custom SLA addendum ready for your team's review.",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_03",
        timestamp: "2026-10-03T08:00:00Z",
        action: "Scheduled with Manual Approval",
        performedBy: "Agent Kumail",
      },
    ],
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T08:00:00Z",
  },

  // 3. LEAD: Michael Brown - Processing / Due (WhatsApp)
  {
    id: "fu_lead_michael_01",
    targetType: "LEAD",
    targetId: "lead_michael",
    targetName: "Michael Brown",
    targetSubtext: "PrimeCare Clinic (Client Lead)",
    clientId: "client_primecare",
    clientName: "PrimeCare Clinic",
    type: "POST_BOOKING_REMINDER",
    priority: "HIGH",
    channel: "whatsapp",
    status: "DUE",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T10:15:00Z",
    dueAt: "2026-10-03T10:30:00Z",
    triggerReason: "Diagnostic health checkup scheduled tomorrow at 11:00 AM.",
    templateId: "tpl_lead_appt_reminder_whatsapp",
    message: "Hello Michael, friendly reminder that your appointment with PrimeCare Clinic is set for tomorrow at 11:00 AM. Reply 1 to confirm or 2 to reschedule.",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_04",
        timestamp: "2026-10-02T15:00:00Z",
        action: "Scheduled automatically",
        performedBy: "Rule: 24-Hour Appointment Confirmation",
      },
    ],
    createdAt: "2026-10-02T15:00:00Z",
    updatedAt: "2026-10-03T10:15:00Z",
  },

  // 4. LEAD: Elena Rostova - Instagram DM (Paused due to Human Takeover)
  {
    id: "fu_lead_elena_01",
    targetType: "LEAD",
    targetId: "lead_elena",
    targetName: "Elena Rostova",
    targetSubtext: "Kashmir Cashmere Co. (Client Lead)",
    clientId: "client_cashmere",
    clientName: "Kashmir Cashmere Co.",
    type: "NO_REPLY_NUDGE",
    priority: "MEDIUM",
    channel: "instagram",
    status: "PAUSED",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T09:00:00Z",
    dueAt: "2026-10-03T09:15:00Z",
    triggerReason: "Human takeover initiated by staff member Fatima. Automated nudge safely halted.",
    templateId: "tpl_lead_no_reply_instagram",
    message: "Hey Elena 👋 We saw your message about bespoke pashmina shawls at Kashmir Cashmere Co. Let us know if you need any assistance choosing the right design!",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_05",
        timestamp: "2026-10-03T08:00:00Z",
        action: "Scheduled",
        performedBy: "Rule: Instagram 4-Hour Re-engagement",
      },
      {
        id: "h_06",
        timestamp: "2026-10-03T08:45:00Z",
        action: "Paused",
        note: "Staff member Fatima initiated human takeover in Instagram thread",
        performedBy: "Omnichannel Safety Guard",
      },
    ],
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T08:45:00Z",
  },

  // 5. LEAD: David Miller - Completed / Sent (Email)
  {
    id: "fu_lead_david_01",
    targetType: "LEAD",
    targetId: "lead_david",
    targetName: "David Miller",
    targetSubtext: "Apex Solar Commercial (Client Lead)",
    clientId: "client_apex_solar",
    clientName: "Apex Solar Commercial",
    type: "NO_REPLY_NUDGE",
    priority: "MEDIUM",
    channel: "email",
    status: "COMPLETED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-02T14:00:00Z",
    dueAt: "2026-10-02T14:30:00Z",
    sentAt: "2026-10-02T14:32:00Z",
    triggerReason: "Commercial roof installation estimate delivered 48h ago.",
    templateId: "tpl_lead_quote_followup_email",
    subject: "Apex Solar Commercial estimate review",
    message: "Hi David, hope the CFO review is going well. Happy to join a 10-minute clarification call on the roof analysis automation ROI.",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_07",
        timestamp: "2026-10-02T14:00:00Z",
        action: "Scheduled",
        performedBy: "Agent Kumail",
      },
      {
        id: "h_08",
        timestamp: "2026-10-02T14:32:00Z",
        action: "Approved and Sent (Simulation)",
        note: "Mock SMTP delivery 200 OK",
        performedBy: "Agent Kumail",
      },
    ],
    createdAt: "2026-10-02T14:00:00Z",
    updatedAt: "2026-10-02T14:32:00Z",
  },

  // 6. PROSPECT: Srinagar Heritage Crafts - Demo Ready (Email)
  {
    id: "fu_prospect_heritage_01",
    targetType: "PROSPECT",
    targetId: "prospect_heritage_crafts",
    targetName: "Srinagar Heritage Crafts",
    targetSubtext: "Handicrafts & Artisans (Prospect)",
    type: "DEMO_PREPARATION",
    priority: "HIGH",
    channel: "email",
    status: "DUE",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-03T10:00:00Z",
    dueAt: "2026-10-03T10:30:00Z",
    triggerReason: "Prospect reached DEMO READY status. AI demo sandbox generated with 92% readiness score.",
    templateId: "tpl_prospect_demo_ready_email",
    subject: "Custom AI Concierge built for Srinagar Heritage Crafts",
    message: "Hi Tariq Ahmad,\n\nWe analyzed Srinagar Heritage Crafts's inbound lead flow in Luxury Handicrafts and built a functioning AI lead-capture prototype.\n\nYou can test it interactively here: https://nexus-ai.local/demo/p_heritage_crafts\n\nWould you have 10 minutes this week to review the revenue impact?\n\nBest,\nKumail\nNEXUS AI",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_09",
        timestamp: "2026-10-03T09:00:00Z",
        action: "Rule Triggered: Auto-Dispatch AI Demo Preview",
        performedBy: "NEXUS AI System",
      },
    ],
    createdAt: "2026-10-03T09:00:00Z",
    updatedAt: "2026-10-03T10:00:00Z",
  },

  // 7. PROSPECT: Gulmarg Alpine Resort - Proposal Nudge (WhatsApp)
  {
    id: "fu_prospect_gulmarg_01",
    targetType: "PROSPECT",
    targetId: "prospect_gulmarg_resort",
    targetName: "Gulmarg Alpine Resort",
    targetSubtext: "Luxury Ski & Spa Resort (Prospect)",
    type: "NO_REPLY_NUDGE",
    priority: "HIGH",
    channel: "whatsapp",
    status: "SCHEDULED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-03T14:00:00Z",
    dueAt: "2026-10-03T14:30:00Z",
    triggerReason: "Proposal sent 48 hours ago ($7,800 ARR deal value). No executive reply yet.",
    templateId: "tpl_prospect_whatsapp_quick_demo",
    message: "Hello Zubair Khan, Kumail from NEXUS AI. We generated an automated 24/7 client booking prototype specifically for Gulmarg Alpine Resort. View the live demo: https://nexus-ai.local/demo/p_gulmarg. Let me know what you think!",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_10",
        timestamp: "2026-10-02T14:00:00Z",
        action: "Scheduled automatically",
        performedBy: "Rule: 48h Post-Proposal Check-in",
      },
    ],
    createdAt: "2026-10-02T14:00:00Z",
    updatedAt: "2026-10-02T14:00:00Z",
  },

  // 8. PROSPECT: Dal Lake Luxury Boathouse - WhatsApp Follow-Up (Sent)
  {
    id: "fu_prospect_boathouse_01",
    targetType: "PROSPECT",
    targetId: "prospect_dal_lake_boathouses",
    targetName: "Dal Lake Luxury Houseboats",
    targetSubtext: "Waterfront Hospitality (Prospect)",
    type: "DEMO_PREPARATION",
    priority: "MEDIUM",
    channel: "whatsapp",
    status: "SENT",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-02T11:00:00Z",
    dueAt: "2026-10-02T11:15:00Z",
    sentAt: "2026-10-02T11:16:30Z",
    triggerReason: "Prospect qualified via Discover search. Autonomous demo share rule.",
    templateId: "tpl_prospect_whatsapp_quick_demo",
    message: "Hello Altaf Hussain, Kumail from NEXUS AI. We generated an automated 24/7 client booking prototype specifically for Dal Lake Luxury Houseboats. View the live demo: https://nexus-ai.local/demo/p_dal_lake. Let me know what you think!",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_11",
        timestamp: "2026-10-02T11:00:00Z",
        action: "Scheduled",
        performedBy: "Rule: Hot Prospect WhatsApp Follow-Up",
      },
      {
        id: "h_12",
        timestamp: "2026-10-02T11:16:30Z",
        action: "Autonomous Simulated Send",
        note: "Delivered via Mock WhatsApp Business Cloud API",
        performedBy: "Autonomous Dispatcher",
      },
    ],
    createdAt: "2026-10-02T11:00:00Z",
    updatedAt: "2026-10-02T11:16:30Z",
  },

  // 9. LEAD: Priya Sharma - Facebook Messenger (Due Today)
  {
    id: "fu_lead_priya_01",
    targetType: "LEAD",
    targetId: "lead_priya",
    targetName: "Priya Sharma",
    targetSubtext: "Pahalgam Pine Retreat (Client Lead)",
    clientId: "client_pahalgam_pine",
    clientName: "Pahalgam Pine Retreat",
    type: "NO_REPLY_NUDGE",
    priority: "MEDIUM",
    channel: "facebook",
    status: "DUE",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T09:45:00Z",
    dueAt: "2026-10-03T10:15:00Z",
    triggerReason: "Inquired about cottage rates on Facebook Messenger, dropped off after greeting.",
    templateId: "tpl_lead_fb_messenger_nudge",
    message: "Hi Priya! Thanks for contacting Pahalgam Pine Retreat on Facebook. Our team is ready to assist you. Do you have any questions about our pricing or cottage availability?",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_13",
        timestamp: "2026-10-03T07:45:00Z",
        action: "Scheduled",
        performedBy: "Rule: Client Lead — Inactivity Nudge",
      },
    ],
    createdAt: "2026-10-03T07:45:00Z",
    updatedAt: "2026-10-03T09:45:00Z",
  },

  // 10. LEAD: Carlos Gomez - Website Chat (Scheduled Upcoming)
  {
    id: "fu_lead_carlos_01",
    targetType: "LEAD",
    targetId: "lead_carlos",
    targetName: "Carlos Gomez",
    targetSubtext: "Alpine Grand Hotel (Client Lead)",
    clientId: "client_hotel_alpine",
    clientName: "Alpine Grand Hotel",
    type: "NO_REPLY_NUDGE",
    priority: "LOW",
    channel: "website",
    status: "SCHEDULED",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T16:00:00Z",
    dueAt: "2026-10-03T16:30:00Z",
    triggerReason: "Website widget conversation paused without email submission.",
    templateId: "tpl_lead_website_live_nudge",
    message: "Hi Carlos, we noticed you paused the conversation. If you still have questions about our seasonal ski packages, I'm here to help right now!",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_14",
        timestamp: "2026-10-03T10:00:00Z",
        action: "Scheduled automatically",
        performedBy: "NEXUS Webhook Resolver",
      },
    ],
    createdAt: "2026-10-03T10:00:00Z",
    updatedAt: "2026-10-03T10:00:00Z",
  },

  // 11. PROSPECT: Snow Valley Adventures - Re-engagement (Scheduled)
  {
    id: "fu_prospect_snow_valley_01",
    targetType: "PROSPECT",
    targetId: "prospect_snow_valley",
    targetName: "Snow Valley Adventures",
    targetSubtext: "Outdoor Expedition Tour Operator",
    type: "RE_ENGAGEMENT",
    priority: "LOW",
    channel: "email",
    status: "SCHEDULED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-04T10:00:00Z",
    dueAt: "2026-10-04T10:30:00Z",
    triggerReason: "Qualified 14 days ago, postponed budget approval until Q4.",
    templateId: "tpl_prospect_reengagement_quarterly",
    subject: "Quick check-in regarding Snow Valley Adventures",
    message: "Hi Bilal Ahmad,\n\nReaching back out to see how your client acquisition and response rates are progressing this quarter at Snow Valley Adventures. We've recently rolled out new WhatsApp automation capabilities that might interest you.\n\nBest,\nKumail",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_15",
        timestamp: "2026-10-01T10:00:00Z",
        action: "Scheduled for Q4",
        performedBy: "Agent Kumail",
      },
    ],
    createdAt: "2026-10-01T10:00:00Z",
    updatedAt: "2026-10-01T10:00:00Z",
  },

  // 12. PROSPECT: Kashmir Valley Dental - Instagram DM Hook (Due Today)
  {
    id: "fu_prospect_dental_01",
    targetType: "PROSPECT",
    targetId: "prospect_kashmir_dental",
    targetName: "Kashmir Valley Dental Group",
    targetSubtext: "Multi-Clinic Dental Healthcare",
    type: "NO_REPLY_NUDGE",
    priority: "HIGH",
    channel: "instagram",
    status: "DUE",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-03T09:30:00Z",
    dueAt: "2026-10-03T10:00:00Z",
    triggerReason: "Target prospect in REPLIED stage. Instagram DM audit prepared.",
    templateId: "tpl_prospect_instagram_dm_hook",
    message: "Hi Kashmir Valley Dental Group team! We noticed high engagement on your recent posts but found delayed responses to direct booking inquiries. We built an AI system for Dental Healthcare brands that answers instantly. Open to a 3-minute video?",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_16",
        timestamp: "2026-10-03T08:00:00Z",
        action: "Audit Generated & Follow-Up Scheduled",
        performedBy: "Business Analysis Engine",
      },
    ],
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T09:30:00Z",
  },

  // 13. LEAD: Aamir Malik - Failed / Retryable (WhatsApp)
  {
    id: "fu_lead_aamir_01",
    targetType: "LEAD",
    targetId: "lead_aamir",
    targetName: "Aamir Malik",
    targetSubtext: "PrimeCare Clinic (Client Lead)",
    clientId: "client_primecare",
    clientName: "PrimeCare Clinic",
    type: "FEEDBACK_CHECKIN",
    priority: "MEDIUM",
    channel: "whatsapp",
    status: "FAILED",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T08:00:00Z",
    dueAt: "2026-10-03T08:15:00Z",
    triggerReason: "Post-consultation satisfaction check-in.",
    templateId: "tpl_lead_satisfaction_checkin",
    message: "Hi Aamir, thank you for choosing PrimeCare Clinic! On a scale of 1-5, how was your experience with our team today?",
    retryCount: 2,
    maxRetries: 3,
    lastError: "Mock Gateway Error 504: Simulated WhatsApp rate limit timeout",
    history: [
      {
        id: "h_17",
        timestamp: "2026-10-03T08:00:00Z",
        action: "Scheduled",
        performedBy: "Rule: Post-Service Feedback Check-In",
      },
      {
        id: "h_18",
        timestamp: "2026-10-03T08:16:00Z",
        action: "Attempt 1 Failed",
        note: "Simulated network timeout",
        performedBy: "Dispatcher",
      },
      {
        id: "h_19",
        timestamp: "2026-10-03T08:21:00Z",
        action: "Attempt 2 Failed",
        note: "Gateway Error 504: WhatsApp rate limit timeout",
        performedBy: "Dispatcher",
      },
    ],
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T08:21:00Z",
  },

  // 14. LEAD: Leila Chen - Cancelled (Client Lead)
  {
    id: "fu_lead_leila_01",
    targetType: "LEAD",
    targetId: "lead_leila",
    targetName: "Leila Chen",
    targetSubtext: "Alpine Grand Hotel (Client Lead)",
    clientId: "client_hotel_alpine",
    clientName: "Alpine Grand Hotel",
    type: "NO_REPLY_NUDGE",
    priority: "LOW",
    channel: "whatsapp",
    status: "CANCELLED",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-02T16:00:00Z",
    dueAt: "2026-10-02T16:30:00Z",
    triggerReason: "Scheduled follow-up cancelled after lead booked reservation directly online.",
    templateId: "tpl_lead_no_reply_whatsapp",
    message: "Hi Leila! Just checking back from Alpine Grand Hotel regarding your recent inquiry. Would you still like us to hold availability for you?",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_20",
        timestamp: "2026-10-02T15:00:00Z",
        action: "Scheduled",
        performedBy: "Rule: 2-Hour No Reply Nudge",
      },
      {
        id: "h_21",
        timestamp: "2026-10-02T15:40:00Z",
        action: "Cancelled",
        note: "Direct booking confirmed in PMS. Follow-up obsolete.",
        performedBy: "Event Sync Worker",
      },
    ],
    createdAt: "2026-10-02T15:00:00Z",
    updatedAt: "2026-10-02T15:40:00Z",
  },

  // 15. PROSPECT: Royal Saffron Exporters - Proposal Review (Upcoming)
  {
    id: "fu_prospect_saffron_01",
    targetType: "PROSPECT",
    targetId: "prospect_royal_saffron",
    targetName: "Royal Saffron Exporters",
    targetSubtext: "Premium Agriculture Export",
    type: "NO_REPLY_NUDGE",
    priority: "HIGH",
    channel: "email",
    status: "SCHEDULED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-04T11:00:00Z",
    dueAt: "2026-10-04T11:30:00Z",
    triggerReason: "Proposal delivered. Follow-up scheduled for Day 3.",
    templateId: "tpl_prospect_proposal_checkin",
    subject: "Quick question on our NEXUS AI proposal for Royal Saffron Exporters",
    message: "Hi Mohammad Wani,\n\nFollowing up on the proposal sent for Royal Saffron Exporters. Did your executive team have a chance to review the multi-channel integration timeline?\n\nHappy to hop on a quick call if you need any adjustments.\n\nWarmly,\nKumail",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_22",
        timestamp: "2026-10-01T11:00:00Z",
        action: "Scheduled",
        performedBy: "Agent Kumail",
      },
    ],
    createdAt: "2026-10-01T11:00:00Z",
    updatedAt: "2026-10-01T11:00:00Z",
  },

  // 16. LEAD: Omar Farooq - Due Today (WhatsApp)
  {
    id: "fu_lead_omar_01",
    targetType: "LEAD",
    targetId: "lead_omar",
    targetName: "Omar Farooq",
    targetSubtext: "Kashmir Cashmere Co. (Client Lead)",
    clientId: "client_cashmere",
    clientName: "Kashmir Cashmere Co.",
    type: "NO_REPLY_NUDGE",
    priority: "MEDIUM",
    channel: "whatsapp",
    status: "DUE",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-03T10:10:00Z",
    dueAt: "2026-10-03T10:40:00Z",
    triggerReason: "Inquired on WhatsApp for bulk corporate gifts. Inactive 3 hours.",
    templateId: "tpl_lead_no_reply_whatsapp",
    message: "Hi Omar! Just checking back from Kashmir Cashmere Co. regarding your recent inquiry. Would you still like us to hold availability for you?",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_23",
        timestamp: "2026-10-03T07:10:00Z",
        action: "Scheduled automatically",
        performedBy: "Rule: 2-Hour No Reply Nudge (WhatsApp)",
      },
    ],
    createdAt: "2026-10-03T07:10:00Z",
    updatedAt: "2026-10-03T10:10:00Z",
  },

  // 17. PROSPECT: Himalaya Eco Trekking - Won / Completed
  {
    id: "fu_prospect_trekking_01",
    targetType: "PROSPECT",
    targetId: "prospect_himalaya_trek",
    targetName: "Himalaya Eco Trekking",
    targetSubtext: "Adventure Travel & Eco-Tours",
    type: "DEMO_PREPARATION",
    priority: "HIGH",
    channel: "email",
    status: "COMPLETED",
    automationMode: "MANUAL_APPROVAL",
    scheduledAt: "2026-10-01T10:00:00Z",
    dueAt: "2026-10-01T10:30:00Z",
    sentAt: "2026-10-01T10:28:00Z",
    triggerReason: "Demo delivery follow-up resulted in signed contract.",
    templateId: "tpl_prospect_demo_ready_email",
    subject: "Custom AI Concierge built for Himalaya Eco Trekking",
    message: "Hi Shabir, hope the demo proved how easily NEXUS captures trekking inquiries. Let's get your production account connected!",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_24",
        timestamp: "2026-10-01T10:28:00Z",
        action: "Sent & Deal Won",
        performedBy: "Agent Kumail",
      },
    ],
    createdAt: "2026-10-01T09:00:00Z",
    updatedAt: "2026-10-01T10:28:00Z",
  },

  // 18. LEAD: Fatima Zahra - Scheduled Upcoming (WhatsApp)
  {
    id: "fu_lead_fatima_01",
    targetType: "LEAD",
    targetId: "lead_fatima",
    targetName: "Fatima Zahra",
    targetSubtext: "PrimeCare Clinic (Client Lead)",
    clientId: "client_primecare",
    clientName: "PrimeCare Clinic",
    type: "POST_BOOKING_REMINDER",
    priority: "HIGH",
    channel: "whatsapp",
    status: "SCHEDULED",
    automationMode: "AUTONOMOUS",
    scheduledAt: "2026-10-04T08:00:00Z",
    dueAt: "2026-10-04T08:30:00Z",
    triggerReason: "Dental cleaning appointment confirmation 24h prior.",
    templateId: "tpl_lead_appt_reminder_whatsapp",
    message: "Hi Fatima, friendly reminder that your appointment with PrimeCare Clinic is set for tomorrow at 9:00 AM. Reply 1 to confirm or 2 to reschedule.",
    retryCount: 0,
    maxRetries: 3,
    history: [
      {
        id: "h_25",
        timestamp: "2026-10-03T08:00:00Z",
        action: "Scheduled automatically",
        performedBy: "Rule: 24-Hour Appointment Confirmation",
      },
    ],
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T08:00:00Z",
  },
];

export const initialMockAutomationRuns: AutomationRun[] = [
  {
    id: "run_001",
    ruleId: "rule_lead_2h_whatsapp_nudge",
    ruleName: "Client Lead — 2-Hour No Reply Nudge (WhatsApp)",
    targetType: "LEAD",
    targetId: "lead_sarah",
    targetName: "Sarah Johnson",
    triggerEvent: "NO_REPLY_120_MIN",
    status: "SUCCESS",
    reason: "Scheduled follow-up fu_lead_sarah_01 (autonomous mode)",
    followUpId: "fu_lead_sarah_01",
    timestamp: "2026-10-03T09:30:00Z",
    details: { delayMinutes: 120, channel: "whatsapp" },
  },
  {
    id: "run_002",
    ruleId: "rule_lead_human_handoff_pause",
    ruleName: "Safety Rule — Pause Automated Follow-ups on Human Takeover",
    targetType: "LEAD",
    targetId: "lead_elena",
    targetName: "Elena Rostova",
    triggerEvent: "HUMAN_HANDOFF_ACTIVATED",
    status: "SUCCESS",
    reason: "Suspended 1 active follow-up (fu_lead_elena_01) due to live staff takeover",
    followUpId: "fu_lead_elena_01",
    timestamp: "2026-10-03T08:45:00Z",
    details: { agent: "Fatima", channel: "instagram" },
  },
  {
    id: "run_003",
    ruleId: "rule_prospect_demo_ready_email",
    ruleName: "Nexus Prospect — Auto-Dispatch AI Demo Preview",
    targetType: "PROSPECT",
    targetId: "prospect_heritage_crafts",
    targetName: "Srinagar Heritage Crafts",
    triggerEvent: "PROSPECT_STATUS_CHANGED",
    status: "SUCCESS",
    reason: "Created follow-up fu_prospect_heritage_01 with manual approval flag",
    followUpId: "fu_prospect_heritage_01",
    timestamp: "2026-10-03T09:00:00Z",
    details: { oldStatus: "RESEARCHING", newStatus: "DEMO READY" },
  },
  {
    id: "run_004",
    ruleId: "rule_lead_2h_whatsapp_nudge",
    ruleName: "Client Lead — 2-Hour No Reply Nudge (WhatsApp)",
    targetType: "LEAD",
    targetId: "lead_sarah",
    targetName: "Sarah Johnson",
    triggerEvent: "NO_REPLY_120_MIN",
    status: "DUPLICATE",
    reason: "Idempotency key matched: follow-up fu_lead_sarah_01 already active for trigger event",
    timestamp: "2026-10-03T09:35:00Z",
    details: { idempotencyKey: "rule_lead_2h_whatsapp_nudge:lead_sarah:NO_REPLY_120_MIN" },
  },
  {
    id: "run_005",
    ruleId: "rule_lead_appt_reminder_24h",
    ruleName: "Client Lead — 24-Hour Appointment Confirmation",
    targetType: "LEAD",
    targetId: "lead_michael",
    targetName: "Michael Brown",
    triggerEvent: "APPOINTMENT_UPCOMING",
    status: "SUCCESS",
    reason: "Scheduled reminder fu_lead_michael_01 for PrimeCare Clinic",
    followUpId: "fu_lead_michael_01",
    timestamp: "2026-10-02T15:00:00Z",
    details: { apptDate: "2026-10-04", apptTime: "11:00 AM" },
  },
  {
    id: "run_006",
    ruleId: "rule_lead_post_service_feedback",
    ruleName: "Client Lead — Post-Service Feedback Check-In",
    targetType: "LEAD",
    targetId: "lead_aamir",
    targetName: "Aamir Malik",
    triggerEvent: "LEAD_QUALIFIED",
    status: "FAILED",
    reason: "Mock Gateway Error 504: WhatsApp rate limit timeout during dispatch",
    followUpId: "fu_lead_aamir_01",
    timestamp: "2026-10-03T08:21:00Z",
    details: { retryCount: 2, error: "HTTP 504 Gateway Timeout" },
  },
  {
    id: "run_007",
    ruleId: "rule_prospect_whatsapp_hot_lead",
    ruleName: "Nexus Prospect — Hot Prospect WhatsApp Follow-Up",
    targetType: "PROSPECT",
    targetId: "prospect_dal_lake_boathouses",
    targetName: "Dal Lake Luxury Houseboats",
    triggerEvent: "PROSPECT_STATUS_CHANGED",
    status: "SUCCESS",
    reason: "Dispatched WhatsApp demo message autonomously",
    followUpId: "fu_prospect_boathouse_01",
    timestamp: "2026-10-02T11:16:30Z",
    details: { dealValue: 6200, channel: "whatsapp" },
  },
  {
    id: "run_008",
    ruleId: "rule_lead_instagram_inactivity",
    ruleName: "Client Lead — Instagram 4-Hour Re-engagement",
    targetType: "LEAD",
    targetId: "lead_james",
    targetName: "James Wilson",
    triggerEvent: "NO_REPLY_240_MIN",
    status: "SKIPPED",
    reason: "Condition not met: Channel is Website, rule requires Instagram",
    timestamp: "2026-10-03T07:15:00Z",
    details: { leadChannel: "website" },
  },
  {
    id: "run_009",
    ruleId: "rule_lead_2h_whatsapp_nudge",
    ruleName: "Client Lead — 2-Hour No Reply Nudge (WhatsApp)",
    targetType: "LEAD",
    targetId: "lead_omar",
    targetName: "Omar Farooq",
    triggerEvent: "NO_REPLY_120_MIN",
    status: "SUCCESS",
    reason: "Scheduled follow-up fu_lead_omar_01 for Kashmir Cashmere Co.",
    followUpId: "fu_lead_omar_01",
    timestamp: "2026-10-03T07:10:00Z",
    details: { delayMinutes: 120 },
  },
  {
    id: "run_010",
    ruleId: "rule_prospect_proposal_48h_nudge",
    ruleName: "Nexus Prospect — 48h Post-Proposal Check-in",
    targetType: "PROSPECT",
    targetId: "prospect_gulmarg_resort",
    targetName: "Gulmarg Alpine Resort",
    triggerEvent: "PROSPECT_STATUS_CHANGED",
    status: "SUCCESS",
    reason: "Created pending follow-up fu_prospect_gulmarg_01",
    followUpId: "fu_prospect_gulmarg_01",
    timestamp: "2026-10-02T14:00:00Z",
    details: { dealValue: 7800 },
  },
];

export const initialMockSuggestions: FollowUpSuggestion[] = [
  {
    id: "sug_01",
    targetType: "LEAD",
    targetId: "lead_sarah",
    targetName: "Sarah Johnson",
    targetSubtext: "Alpine Grand Hotel",
    clientId: "client_hotel_alpine",
    clientName: "Alpine Grand Hotel",
    recommendedType: "QUOTE_EXCLUSIVITY_EXPIRATION",
    recommendedChannel: "whatsapp",
    confidenceScore: 0.96,
    urgency: "URGENT",
    rationale: "Sarah asked for the Presidential Suite pricing 3 hours ago. Room lock policy requires follow-up before 5:00 PM to protect inventory.",
    suggestedDelayHours: 0,
    draftMessage: "Hi Sarah! Just checking in — we have one remaining Presidential Suite available for this weekend at Alpine Grand Hotel. Would you like me to hold it for you?",
  },
  {
    id: "sug_02",
    targetType: "PROSPECT",
    targetId: "prospect_heritage_crafts",
    targetName: "Srinagar Heritage Crafts",
    targetSubtext: "Handicrafts & Artisans",
    recommendedType: "DEMO_PREPARATION",
    recommendedChannel: "email",
    confidenceScore: 0.93,
    urgency: "HIGH",
    rationale: "High Instagram lead leakage identified (4.2h average response time). Sending interactive demo link demonstrates instant ROI.",
    suggestedDelayHours: 1,
    draftMessage: "Hi Tariq Ahmad, we analyzed Srinagar Heritage Crafts's inbound lead flow in Luxury Handicrafts and built a functioning AI prototype. Check the live demo: https://nexus-ai.local/demo/p_heritage_crafts",
  },
  {
    id: "sug_03",
    targetType: "LEAD",
    targetId: "lead_michael",
    targetName: "Michael Brown",
    targetSubtext: "PrimeCare Clinic",
    clientId: "client_primecare",
    clientName: "PrimeCare Clinic",
    recommendedType: "POST_BOOKING_REMINDER",
    recommendedChannel: "whatsapp",
    confidenceScore: 0.91,
    urgency: "HIGH",
    rationale: "Appointment scheduled for tomorrow morning. Clinical reminders reduce patient no-show rates by 42%.",
    suggestedDelayHours: 0,
    draftMessage: "Hello Michael, friendly reminder that your appointment with PrimeCare Clinic is set for tomorrow at 11:00 AM. Reply 1 to confirm or 2 to reschedule.",
  },
  {
    id: "sug_04",
    targetType: "PROSPECT",
    targetId: "prospect_gulmarg_resort",
    targetName: "Gulmarg Alpine Resort",
    targetSubtext: "Luxury Ski & Spa Resort",
    recommendedType: "NO_REPLY_NUDGE",
    recommendedChannel: "whatsapp",
    confidenceScore: 0.88,
    urgency: "HIGH",
    rationale: "Executive proposal delivered 48 hours ago. High estimated annual value ($7,800). WhatsApp direct nudge has 78% read rate.",
    suggestedDelayHours: 2,
    draftMessage: "Hello Zubair Khan, Kumail from NEXUS AI. We generated an automated 24/7 client booking prototype for Gulmarg Alpine Resort. View live: https://nexus-ai.local/demo/p_gulmarg",
  },
];
